var e;function aa(b){f(b,"fill")}function ba(b){f(b,"stroke")}function ca(b){f(b,"stroke-width")}function g(b,c,d){b.setAttribute(c,d);return b}function da(b,c){return g(b,"class",c)}function h(b){return b.getAttribute("id")}function ea(b,c){return g(b,"dur",c)}function l(b,c){m(b,"fill",c)}function fa(b,c){aa(b);return g(b,"fill","url(#"+c+")")}function p(b,c){return g(b,"height",c)}function ga(b,c){m(b,"marker-start","url(#"+c+")")}
function ha(b,c,d){return p(q(s(t(b,c.x-d),c.y-d),c.width+d+d),c.height+d+d)}function ia(b,c){return ha(ja(b,"rect"),b.getBBox(),c)}function x(b,c){return ha(z(b,"rect"),b.getBBox(),c)}function ka(b){return ha(z(b,"rect"),b.getBBox(),0)}function la(b,c){m(b,"font-family",c)}function ma(b,c){na(b,"font-size");return g(b,"font-size",c)}function B(b,c){return g(b,"from",c)}function C(b,c){m(b,"stroke",c)}function D(b,c){return m(b,"stroke-width",c)}function oa(b,c){return g(b,"to",c)}
function E(b,c){return g(b,"transform",c)}function pa(b){return m(b,"vector-effect","non-scaling-stroke")}function q(b,c){return g(b,"width",c)}function t(b,c){return g(b,"x",c)}function s(b,c){return g(b,"y",c)}function F(b,c){var d=b.getAttribute(c);return null==d||""==d?0:parseFloat(d)}function qa(b){return b.getAttribute("class")}function ea(b,c){return g(b,"dur",c)}function G(b){return H(b,"fill")}function ra(b){return sa(H(b,"marker-start"))}function ta(){return H(I.b,"stroke")}
function ua(b){return H(b,"stroke-dasharray")}function J(b){return H(b,"stroke-width")}function K(b){return F(b,"height")}function L(b){return F(b,"y")}function va(b,c){return b.appendChild(b.ownerDocument.createElementNS("http://www.w3.org/2000/svg",c))}function M(b){var c=document.getElementById(b);if(null==c)throw"Element '"+b+"' not found";return c}
function O(b,c){for(var d=b.firstChild;null!=d;d=d.nextSibling)if(d.tagName&&d.tagName==c)return d;throw"getFirstChild ("+b+","+c+"), element not found";}function wa(b){for(var c=b.firstChild;null!=c;c=c.nextSibling)if(c.tagName)return c;throw"getFirstChild ("+b+"), element undefined not found";}function xa(b){for(b=b.nextSibling;null!=b;b=b.nextSibling)if(b.tagName&&"rect"==b.tagName)return b;return null}
function z(b,c){for(var d=b.nextSibling;null!=d;d=d.nextSibling)if(d.tagName&&d.tagName==c)return d;throw"getNextSibling ("+b+","+c+"), element not found";}function ya(b){for(var c=b.nextSibling;null!=c;c=c.nextSibling)if(c.tagName)return c;throw"getNextSibling ("+b+"), element not found";}function ja(b,c){for(var d=b.previousSibling;null!=d;d=d.previousSibling)if(d.tagName&&d.tagName==c)return d;throw"getPreviousSibling ("+b+","+c+"), element not found";}
function za(b){for(;null!=b.firstChild;)b.removeChild(b.firstChild)}function Aa(b,c){var d=b.getAttribute("style");if(null!=d&&""!=d){var k=d.indexOf(c+":",0);if(-1!=k){var n=d.indexOf(":",k),k=d.indexOf(";",k);return-1!=k?d.substring(n+1,k):d.substring(n+1,d.length)}}return null}function na(b,c){var d=b.getAttribute("style");if(null!=d&&""!=d){var k=d.indexOf(c+":",0);if(-1!=k){var n=d.indexOf(";",k);-1!=n?g(b,"style",d.substring(0,k)+d.substring(n+1,d.length)):g(b,"style",d.substring(0,k))}}}
function H(b,c){var d=Aa(b,c);return null==d?b.getAttribute(c):d}function m(b,c,d){if(null!=Aa(b,c)){var k=b.getAttribute("style");if(null!=k&&""!=k){var n=k.indexOf(c+":",0);-1!=n?(c=k.indexOf(":",n),n=k.indexOf(";",n),b=-1!=n?g(b,"style",k.substring(0,c+1)+d+k.substring(n,k.length)):g(b,"style",k.substring(0,c+1)+d+";")):b=g(b,"style",c+":"+d+";"+k)}else b=g(b,"style",c+":"+d+";")}else b=g(b,c,d);return b}function f(b,c){null==Aa(b,c)&&b.hasAttribute(c)?b.removeAttribute(c):na(b,c)}
function sa(b){if(null!=b&&"url("==b.substr(0,4)&&-1!=b.indexOf("#")&&-1!=b.indexOf(")")){b=b.substring(b.indexOf("#")+1,b.indexOf(")"));if("'"==b.charAt(b.length-1)||'"'==b.charAt(b.length-1))b=b.substr(0,b.length-1);return b}return null}function Q(b){m(b,"visibility","visible")}function R(b){m(b,"visibility","hidden")}function S(b){b=H(b,"visibility");return null==b||"visible"==b}function Ba(b,c){m(b,"visibility",!0==c?"visible":"hidden")}
function T(b,c){var d=qa(b);da(b,d.substring(0,d.length-1)+c)}function Ca(b,c,d){b.addEventListener(c,d,!1);return b}function U(b,c,d){b.removeEventListener(c,d,!1);return b}function Da(b){b=b.getScreenCTM().inverse();return Math.sqrt(b.a*b.a+b.d*b.d)/Math.SQRT2}
function V(b){if(null==b.ownerDocument)throw"svgtk.getRoot node.ownerDocument is null";if("undefined"!=typeof b.ownerDocument.rootElement&&null!=b.ownerDocument.rootElement)return b.ownerDocument.rootElement;var c=b.Rc;if(null==c){if("svg"!=b.tagName){for(var d=null,c=b.parentNode;null!=c;c=c.parentNode)"svg"==c.tagName&&(d=c);if(null!=d)return d;throw"svgtk.getRoot unexpected node "+b+" "+typeof b.Rc+" tag '"+b.tagName+"' should be'svg'";}return b}for(;null!=c.Rc;)c=c.Rc;if("svg"!=c.tagName)throw"svgtk.getRoot unexpected node "+
c+" tag '"+c.tagName+"' should be 'svg'";return c}function Ea(b,c){var d=b.transform.baseVal,k=d.createSVGTransformFromMatrix(c);0!=d.numberOfItems?(d.insertItemBefore(k,0),d.consolidate()):d.appendItem(k)}function Fa(b,c){var d=b.transform.baseVal,k=d.createSVGTransformFromMatrix(c);d.initialize(k)}
function Ga(b,c,d){var k;k="";for(b=(b<<16)+(c<<8)+d;15<b;)k="0123456789ABCDEF".charAt(b-16*Math.floor(b/16))+k,b=Math.floor(b/16);k="0123456789ABCDEF".charAt(b)+k;b="";for(c=k.length;6>c;c++)b="0"+b;return"#"+b+k}function Ha(b){return"#"==b.charAt(0)&&7==b.length}function Ia(b){return 0==b.indexOf("rgb(")?(b=/(.*?)rgb\((\d+),(\d+),(\d+)\)/.exec(b),null!=b&&5==b.length):!1}function Ja(b){return"#"==b.charAt(0)?b.substring(1,7):b}
var Ka={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",
darkgrey:"#a9a9a9",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",
ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",grey:"#808080",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgreen:"#90ee90",lightgrey:"#d3d3d3",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"},Ca=function(b,c,d){b.addEventListener(c,d,!1);return b},U=function(b,c,d){b.removeEventListener(c,d,!1);return b};
function Ma(b,c){Ca(b,/Firefox/i.test(navigator.userAgent)?"DOMMouseScroll":"mousewheel",c)}function Na(b){return Math.max(-1,Math.min(1,b.wheelDelta||-b.detail))}function Oa(b,c){var d=Math.pow(10,c);return(Math.round(b*d)/d).toFixed(c)}function Pa(b){var c=window.parent;try{return"undefined"!=typeof c[b]}catch(d){return!1}};function Qa(){this.Ia=1;this.$e=this.Ze;this.Fc=this.Lf.bind(this);this.Na=this.uc.bind(this)}e=Qa.prototype;e.f=function(b){this.u=b;return this};e.Pc=function(b){b.stopPropagation();b.preventDefault();var c=V(this.u);this.s=Da(this.u);this.Ia=0;for(var d=1;d>this.s;d/=10)this.Ia+=1;this.Nd=b.clientX;this.Od=b.clientY;Ca(Ca(c,"mousemove",this.Fc),"mouseup",this.Na)};e.Ze=function(b,c){var d=this.u,k=V(d).createSVGMatrix().translate(b,c);Ea(d,k)};
e.Lf=function(b){try{b.stopPropagation();var c=(b.clientX-this.Nd)*this.s,d=(b.clientY-this.Od)*this.s;this.Nd=b.clientX;this.Od=b.clientY;this.$e(c,d)}catch(k){b=V(this.u),U(U(b,"mousemove",this.Fc),"mouseup",this.Na),alert("MovingCtrl :"+k)}};e.uc=function(b){b.stopPropagation();b=V(this.u);U(U(b,"mousemove",this.Fc),"mouseup",this.Na)};function Ra(){}e=Ra.prototype;e.text=null;e.value=0;e.ud=1;e.f=function(b){this.text=b;this.value=parseFloat(this.text.firstChild.data);return this};e.Db=function(b){return 0>=this.ud?parseInt(b):Oa(b,this.ud)};e.g=function(b){this.value=parseFloat(b);this.text.firstChild.data=this.Db(b);return this};e.j=function(){return this.value};function Sa(){this.yc=this.wa.bind(this);this.zc=this.Ff.bind(this)}e=Sa.prototype;e.ma=!0;e.Y=!0;e.i=function(b,c,d,k,n,r,y){this.f(M(b+"-bar"),M(b+"-index"),M(b+"-value"),c,d,k,n,r,y);return this};e.f=function(b,c,d,k,n,r,y,u,A){this.l=b;this.index=c;this.Sb=new Ra;this.Sb.f(d);this.value=d;this.Bd=u;this.Cd=A;this.Y=k;this.nc=!0==this.Y?this.l.getBBox().width:this.l.getBBox().height;this.La=S(this.index);this.setInterval(n,r,y);this.g(this.Ca);return this};
e.setInterval=function(b,c,d){this.Ca=parseFloat(b);this.vb=parseFloat(c);this.wd=Math.min(this.Ca,this.vb);this.vd=Math.max(this.Ca,this.vb);this.Ia=d;this.Sb.ud=d;return this};e.D=function(b){b!=this.ma&&(this.ma=b,!0==b?(this.La&&Q(this.index),Q(this.value)):(R(this.index),R(this.value)));return this};function Ta(b){R(b.index);Q(b.value);b.La=!1}
e.g=function(b){this.ma||this.D(!0);if(b>=this.wd&&b<=this.vd){var c=this.nc*(b-this.Ca)/(this.vb-this.Ca);this.La||Q(this.index);E(this.index,!0==this.Y?"translate("+c+" 0)":"translate(0 "+c+")");!1==this.La&&Q(this.value);this.La=!0}else this.La=!1,R(this.index);this.Sb.g(b);return this};e.j=function(){return this.Sb.j()};
function Ua(b,c){try{if(c.stopPropagation(),c.preventDefault(),b.ma){var d=V(b.l);b.s=Da(b.l);b.Xd=!0==b.Y?c.clientX:c.clientY;b.Yd=parseFloat(b.j());Ca(Ca(d,"mousemove",b.yc),"mouseup",b.zc)}}catch(k){alert("Slider onIndexDown:"+k+" "+a)}}e.Db=function(b){return 0>=this.Ia?parseInt(b):Oa(parseFloat(b),this.Ia)};
e.wa=function(b){try{b.stopPropagation();var c=Math.max(this.wd,Math.min(this.vd,this.Yd+((!0==this.Y?b.clientX:b.clientY)-this.Xd)*this.s/this.nc*(this.vb-this.Ca))),d=this.Db(c);null!=this.Bd?this.Bd(d):this.g(d)}catch(k){b=V(this.l),U(U(b,"mousemove",this.yc),"mouseup",this.zc),alert("Slider onIndexMove:"+k)}};
e.Ff=function(b){try{b.stopPropagation();var c=V(this.l),d=this.Db(Math.max(this.wd,Math.min(this.vd,this.Yd+((!0==this.Y?b.clientX:b.clientY)-this.Xd)*this.s/this.nc*(this.vb-this.Ca))));U(U(c,"mousemove",this.yc),"mouseup",this.zc);null!=this.Cd?this.Cd(d):this.g(d)}catch(k){alert("Slider onIndexUp:"+k)}};function Va(){this.u=this.da=null;return this}Va.prototype.f=function(b){this.u=b;a:{for(b=b.firstChild;null!=b;b=b.nextSibling)if(b.tagName)break a;b=null}a:{for(b=b.nextSibling;null!=b;b=b.nextSibling)if(b.tagName)break a;b=null}this.da=b;ka(z(this.da,"text"));return this};Va.prototype.i=function(b){this.f(M(b));return this};Va.prototype.j=function(){return-1!=qa(this.da).indexOf("1")};Va.prototype.g=function(b){da(this.da,!0==b?qa(this.da).replace("0","1"):qa(this.da).replace("1","0"));return this};
function Wa(){this.k=[];return this}Wa.prototype.i=function(b){this.f(M(b));return this};Wa.prototype.f=function(b){this.u=b;this.k.splice(0,this.k.length);for(b=this.u.firstChild;null!=b;b=b.nextSibling)b.tagName&&"g"==b.tagName&&this.k.push((new Va).f(b));for(b=0;b<this.k.length;b++)if(this.k[b].j()){for(b+=1;b<this.k.length;b++)this.k[b].j()&&this.k[b].g(!1);break}return this};Wa.prototype.P=function(){for(var b=0;b<this.k.length;b++)this.k[b].g(!1);return this};
Wa.prototype.select=function(b){this.P();for(var c=0;c<this.k.length;c++)if(z(this.k[c].da,"text").firstChild.data==b)return this.k[c].g(!0),c;return-1};function Xa(){this.Bc=this.be.bind(this);this.Ac=this.ae.bind(this);this.Mb=this.ma=!0;this.xb=!1;this.ea=0;this.Ya="ABCDEFG"}e=Xa.prototype;e.f=function(b,c){this.text=b;this.rect=z(this.text,"rect");this.W=c;0==this.text.childNodes.length&&this.text.appendChild(this.text.ownerDocument.createTextNode(""));this.Bc=this.be.bind(this);this.Ac=this.ae.bind(this);this.ce=this.Of.bind(this);return this};e.D=function(b){this.ma=b;return this};e.isEnabled=function(){return this.ma};
function Ya(b,c){b.xb=!0;b.Ya=c;b.ea=1;Za(b)}function Za(b){b.j().length<b.Ya.length?$a(b,b.Ya,b.ea):ab(b,b.ea)}function $a(b,c,d){var k=b.text.firstChild.nodeValue;b.text.firstChild.nodeValue=c;c=b.text.getBBox();b.text.firstChild.nodeValue=k;b.ea=d;ha(b.rect,c,b.ea)}function ab(b,c){var d=b.text.getBBox();b.ea=c;ha(b.rect,d,b.ea)}e.j=function(){return this.text.firstChild.nodeValue};e.g=function(b){this.text.firstChild.nodeValue=b;!0==this.xb&&Za(this);return this};
e.onclick=function(b){b.stopPropagation();b.preventDefault();if(this.ma)return window.focus(),Ca(Ca(document.documentElement,"keypress",this.Bc),"keydown",this.Ac),Ca(this.rect,"mouseout",this.ce),this.re=this.text.firstChild.nodeValue,T(this.rect,"2"),!0==this.Mb&&(this.text.firstChild.data=""),!0;throw"field is disabled";};e.Of=function(){this.text.firstChild.nodeValue=this.re;bb(this);T(this.rect,"0")};
function bb(b){U(U(document.documentElement,"keypress",b.Bc),"keydown",b.Ac);U(b.rect,"mouseout",b.ce)}e.ae=function(b){var c=b.charCode|b.keyCode;b.stopPropagation();8==c&&(c=this.text.firstChild.data.length,0<c&&(this.text.firstChild.deleteData(c-1,1),!0==this.xb&&c>this.Ya.length&&ab(this,this.ea)),b.returnValue=!1)};
e.be=function(b){var c=b.charCode|b.keyCode;b.stopPropagation();if(13==c||10==c){if(bb(this),T(this.rect,"0"),void 0!=this.W)try{this.g(this.W(b,this.text.firstChild.data,this.re))}catch(d){this.g(this.fh)}}else 31<c&&127!=c&&65535>c&&(this.text.firstChild.appendData(String.fromCharCode(c)),!0==this.xb&&this.text.firstChild.data.length>this.Ya.length&&ab(this,this.ea));return b.returnValue=!1};function cb(){this.name="";this.l=this.Ea=this.e=this.ka=null;this.zd=!1;this.scale=1;this.Wd=this.Zd=0;this.$d=this.ef.bind(this);this.Na=this.uc.bind(this);this.pa=this.hb.bind(this);return this}e=cb.prototype;e.f=function(b,c,d,k,n){if(k.parentNode!=d.parentNode)throw"VerticalBar.init : bar's parent and barBack's parent must be equals";this.Re=k.parentNode;this.ka=b;this.e=c;this.Ea=d;this.l=k;this.zd=n;db(this);Ma(this.Re,this.pa);!0==this.zd&&Ma(this.e,this.pa);return this};
e.i=function(b,c){this.name=b;return this.f(wa(M(b+"-clip")),M(b+"-area"),M(b+"-bar-back"),M(b+"-bar"),c)};e.ec=function(){try{return"rect"==this.ka.tagName?{x:F(this.ka,"x"),y:L(this.ka),width:F(this.ka,"width"),height:K(this.ka)}:this.ka.getBBox()}catch(b){return M(h(this.ka)+"-show").getBBox()}};
function db(b){var c=b.ec(),d=c.height,c=c.y,k=F(b.Ea,"x"),n=F(b.Ea,"width"),r=ya(b.Ea),y=ya(r),u=ya(y),A=b.e.getBBox().height,N=0;b.scale=A/(d-2*n);t(s(q(p(b.l,Math.min((d-2*n)*d/A,d-2*n)),n),c+n),k);p(s(b.Ea,c),d);E(r,"translate("+k+","+(c+n)+") scale("+n+")");E(y,"translate("+k+","+(c+d-n)+")  scale("+n+")");b.Z=c+n;b.fb=b.Z+d-2*n-K(b.l);for(r=wa(u);null!=r;r=r.nextSibling)r.tagName&&"rect"==r.tagName&&N++;r=wa(u);k=F(b.Ea,"x");for(b=(d-2*n)/N;null!=r;r=r.nextSibling)r.tagName&&"rect"==r.tagName&&
(p(q(s(t(r,k),c+n),n),b),c+=b)}e.scrollTo=function(b){var c=Math.max(this.Z,Math.min(this.fb,b));this.l.y.baseVal.value=c;b=this.e;c=(this.Z-c)*this.scale;c=V(b).createSVGMatrix().translate(0,c);Fa(b,c);return this};e.qa=function(){return this.scrollTo(this.Z)};e.ra=function(){return this.scrollTo(this.fb)};function eb(b){b.scrollTo(L(b.l)-K(b.l)/2)}function fb(b){b.scrollTo(L(b.l)+K(b.l)/2)}function gb(b,c){b.scrollTo(L(c.target)-K(b.l)/2)}
function hb(b,c){var d=b.l.ownerDocument.rootElement;c.stopPropagation();c.preventDefault();b.Zd=c.clientY;b.Wd=b.l.y.baseVal.value;b.s=Da(b.l);Ca(Ca(d,"mousemove",b.$d),"mouseup",b.Na)}e.ef=function(b){this.scrollTo(this.Wd+(b.clientY-this.Zd)*this.s)};e.uc=function(){U(U(this.l.ownerDocument.rootElement,"mousemove",this.$d),"mouseup",this.Na)};e.hb=function(b){b.stopPropagation();b=(this.Z-this.fb)*Na(b)/10;this.scrollTo(this.l.y.baseVal.value+b)};function ib(){this.Ma=null;this.oa=!1;return this}e=ib.prototype;e.i=function(b,c,d){this.name=b;this.e=M(b+"-area");this.clip=wa(M(b+"-clip"));this.W=c;this.oa=d&&!0==d;this.selected=!0==this.oa?[]:null;this.B=(new cb).i(b,!0);jb(this);return this};e.f=function(){jb(this);return this};e.clear=function(){za(this.e);this.Ma=null;this.selected=!0==this.oa?[]:null};
e.ec=function(){try{return"rect"==this.clip.tagName?{x:F(this.clip,"x"),y:L(this.clip),width:F(this.clip,"width"),height:K(this.clip)}:this.clip.getBBox()}catch(b){return M(h(this.clip)+"-show").getBBox()}};function jb(b){for(var c=b.ec().width,d=b.e.firstChild,k=-1;null!=d;d=d.nextSibling)if(d.tagName&&"g"==d.tagName){var n=O(d,"text"),k=k+n.getBBox().height;s(n,k);q(ka(n),c);q(ia(n,0),c)}db(b.B)}function kb(b){b=qa(b);return"1"==(null==b?null:b.charAt(b.length-1))}
function lb(b,c){for(var d=b.e.firstChild,k=0;null!=d;d=d.nextSibling)if(d.tagName&&"g"==d.tagName){if(O(d,"text")==c)return k;k++}return-1}function mb(b,c){for(var d=b.e.firstChild;null!=d;d=d.nextSibling)if(d.tagName&&"g"==d.tagName&&O(d,"text").firstChild.data==c)return d;return null}e.findText=function(b){for(var c=this.e.firstChild;null!=c;c=c.nextSibling)if(c.tagName&&"g"==c.tagName&&O(c,"text").firstChild.data==b)return O(c,"text");return null};
e.removeNode=function(b){b=mb(this,b);null!=b&&(b.parentNode.removeChild(b),jb(this));return b};
function nb(b,c){try{var d=ja(c.target,"text");if(!0==b.oa)if(!0==c.shiftKey&&null!=b.Ma){var k=lb(b,b.Ma);if(-1!=k){var n=lb(b,d),r=Math.max(n,k)-Math.min(n,k);b.Ma=d;for(!1==kb(d)&&b.W(d,!0,!1);0<r;)d=n>=k?O(ja(d.parentNode,"g"),"text"):O(z(d.parentNode,"g"),"text"),!1==kb(d)&&b.W(d,!0,!1),r--}else b.W(d,c.ctrlKey,kb(d)),b.Ma=d}else b.W(d,c.ctrlKey,kb(d)),b.Ma=d;else b.W(d,c.ctrlKey,kb(d))}catch(y){alert("onDownN "+y)}}function ob(b){b=ja(b.target,"text");-1==qa(b).indexOf("1")&&pb(b,"2")}
function qb(b){b=ja(b.target,"text");-1==qa(b).indexOf("1")&&pb(b,"0")}e.P=function(){if(!0==this.oa){for(var b=0;b<this.selected.length;b++)pb(this.selected[b],"0");this.selected.splice(0,this.selected.length)}else null!=this.selected&&(pb(this.selected,"0"),this.selected=null)};function pb(b,c){T(b,c);T(ja(b,"rect"),c)}
e.g=function(b){if(!0==this.oa){if(this.P(),null!=b)for(var c=0;c<b.length;c++){var d=this.findText(b[c]);null!=d&&(pb(d,"1"),this.selected.push(d))}}else b=this.findText(b),this.P(),null!=b&&(!0==this.oa?this.selected[0]=b:this.selected=b,pb(b,"1"))};e.j=function(){if(!0==this.oa){for(var b=[],c=0;c<this.selected.length;c++)b[c]=this.selected[c].firstChild.data;return b}return null!=this.selected?this.selected.firstChild.data:null};e.ra=function(){this.B.ra()};e.qa=function(){this.B.qa()};var W={zb:"white ghostwhite snow azure aliceblue mintcream ivory floralwhite honeydew lavenderblush whitesmoke lightcyan lavender seashell lightyellow oldlace linen mistyrose cornsilk beige lightgoldenrodyellow papayawhip antiquewhite lemonchiffon blanchedalmond bisque pink gainsboro lightgray silver powderblue paleturquoise lightblue lightskyblue skyblue lightsteelblue violet lightpink svgctrl.ColorChoosertle plum moccasin palegoldenrod peachpuff wheat navajowhite khaki palegreen lightgreen tan burlywood lightcoral darkgray darkseagreen rosybrown gray aquamarine turquoise mediumturquoise aqua darkturquoise cornflowerblue deepskyblue dodgerblue mediumaquamarine mediumspringgreen steelblue cadetblue lightslategray slategray lightseagreen darkcyan teal orchid mediumpurple mediumorchid fuchsia blueviolet darkorchid darkviolet hotpink palevioletred deeppink mediumvioletred darkmagenta purple mediumslateblue royalblue slateblue blue mediumblue darkslateblue indigo darkblue navy lightsalmon sandybrown darksalmon salmon darkkhaki yellow gold greenyellow yellowgreen goldenrod peru orange darkorange darkgoldenrod olive springgreen mediumseagreen seagreen chartreuse lawngreen limegreen lime olivedrab forestgreen green coral tomato indianred chocolate orangered sienna saddlebrown crimson red firebrick brown darkred maroon dimgray darkslategray midnightblue darkolivegreen darkgreen black".split(" "),
ta:null,$a:null,Ad:null,ca:!1,Da:!0,Za:!1,dd:null,Yb:null,Y:!1,f:function(b){W.Pa=M("colorchooser-panel");W.name=M("colorchooser-map-name");W.value=M("colorchooser-map-value");W.rect=M("colorchooser-map-rect");W.Fd=M("colorchooser-map-red");W.Ed=M("colorchooser-map-green");W.Dd=M("colorchooser-map-blue");W.Aa=(new Sa).i("colorchooser-map-red",!0,0,255,0,W.sg,null);W.za=(new Sa).i("colorchooser-map-green",!0,0,255,0,W.rg,null);W.o=(new Sa).i("colorchooser-map-blue",!0,0,255,0,W.pg,null);W.cd=(new Xa).f(M("colorchooser-map-red-value"),
W.wg);W.hc=(new Xa).f(M("colorchooser-map-green-value"),W.Se);W.Xb=(new Xa).f(M("colorchooser-map-blue-value"),W.Ke);W.rb=(new Wa).i("colorchooser-format");W.af=(new Qa).f(W.Pa);W.Y=b&&!0==b;W.load();x(M("colorchooser-map-close"),1);$a(W.cd,"255",1);$a(W.hc,"255",1);$a(W.Xb,"255",1);W.cd.Mb=!0;W.hc.Mb=!0;W.Xb.Mb=!0;return W},load:function(){for(var b=O(M("colorchooser-map"),"rect"),c=0,d=0,k=0,n=W.Y?17:10,c=0;c<W.zb.length&&null!=b;c++)l(p(q(s(t(b,d),k),4.5),4),W.zb[c]),d+=4.5,0==(c+1)%n&&(d=0,k+=
4),b=xa(b);b=O(W.Fd,"rect");d=1.6;v=0;for(w=2.2;null!=b;b=xa(b))l(p(q(s(t(b,d),0),w),3),Ga(v,0,0)),d+=w,v+=16;b=O(W.Ed,"rect");d=1.6;v=0;for(w=2.2;null!=b;b=xa(b))l(p(q(s(t(b,d),0),w),3),Ga(0,v,0)),d+=w,v+=16;b=O(W.Dd,"rect");d=1.6;v=0;for(w=2.2;null!=b;b=xa(b))l(p(q(s(t(b,d),0),w),3),Ga(0,0,v)),d+=w,v+=16;W.Y?(E(M("colorchooser-rgb-sliders"),"translate(85 15)"),E(M("colorchooser-format"),"translate(83.5 41) scale(0.8)"),E(M("colorchooser-actions"),"translate(82.5 43)"),p(q(M("colorchooser-panel-rect"),
136),55),t(s(M("colorchooser-map-name"),36),76.5)):(E(M("colorchooser-rgb-sliders"),"translate(2.5 76)"),E(M("colorchooser-format"),"translate(1 102) scale(0.8)"),E(M("colorchooser-actions"),"translate(0 104)"),p(q(M("colorchooser-panel-rect"),52),116),t(s(M("colorchooser-map-name"),60),46))},Og:function(b){for(var c=O(M("colorchooser-map"),"rect"),d=0;d<W.zb.length&&null!=c;d++){if(W.zb[d]==b)return c;c=xa(c)}return null},wg:function(b,c,d){b=RegExp("[0-9]+","g").exec(c);return null!=b&&1==b.length&&
b[0].length==c.length?(c=Math.max(0,Math.min(255,parseInt(c))),W.T(c,W.za.j(),W.o.j()),c):d},Se:function(b,c,d){b=RegExp("[0-9]+","g").exec(c);return null!=b&&1==b.length&&b[0].length==c.length?(c=Math.max(0,Math.min(255,parseInt(c))),W.T(W.Aa.j(),c,W.o.j()),c):d},Ke:function(b,c,d){b=RegExp("[0-9]+","g").exec(c);return null!=b&&1==b.length&&b[0].length==c.length?(c=Math.max(0,Math.min(255,parseInt(c))),W.T(W.Aa.j(),W.za.j(),c),c):d},show:function(b,c,d,k,n){var r=M("colorchooser-gs"),y=W.Pa;r.transform.baseVal.clear();
y.transform.baseVal.clear();var u=V(y).createSVGMatrix().translate(b,c);Ea(y,u);u=V(r).createSVGMatrix().scale(d);Ea(r,u);r=y.getBBox();Q(p(q(s(t(y,b),c),r.width+2*d),r.height+2*d));W.dd=k;W.Yb=n},bb:function(){R(M("colorchooser-panel"))},oh:function(b){M("colorchooser-title").firstChild.data=b},gf:function(){null!=W.Yb?W.Yb():W.bb()},Ra:function(b){var c,d;void 0!=Ka[b]?(W.rb.select("name"),W.ca=!0,W.Da=!1,W.Za=!1,W.ed(b)):Ha(b)?(W.rb.select("hex"),W.ca=!1,W.Da=!0,W.Za=!1,W.T(ColorHexToR(b),ColorHexToG(b),
ColorHexToB(b))):Ia(b)&&(d=/(.*?)rgb\((\d+),(\d+),(\d+)\)/.exec(b),b=parseInt(d[2]),c=parseInt(d[3]),d=parseInt(d[4]),W.rb.select("rgb"),W.ca=!1,W.Da=!1,W.Za=!0,W.T(b,c,d))},T:function(b,c,d){W.$a={O:b,u:c,G:d};W.Ad=Ga(b,c,d);var k=W.Da||W.ca?W.Ad:"rgb("+b+","+c+","+d+")";l(W.rect,k);W.value.firstChild.data=k;W.Aa.g(b);W.za.g(c);W.o.g(d);for(var n=O(W.Fd,"rect"),k=0;null!=n;n=xa(n))l(n,Ga(k,c,d)),k+=16;n=O(W.Ed,"rect");for(k=0;null!=n;n=xa(n))l(n,Ga(b,k,d)),k+=16;n=O(W.Dd,"rect");for(k=0;null!=n;n=
xa(n))l(n,Ga(b,c,k)),k+=16},Vg:function(){return{O:W.Aa.j(),u:W.za.j(),G:W.o.j()}},Nb:function(){W.ca&&(W.rb.select("hex"),W.ca=!1,W.Da=!0,W.Za=!1)},ed:function(b){W.T(parseInt(Ja(Ka[b]).substring(0,2),16),parseInt(Ja(Ka[b]).substring(2,4),16),parseInt(Ja(Ka[b]).substring(4,6),16));W.ta=b;W.ca&&(l(W.rect,b),W.value.firstChild.data=b)},Ob:function(b){W.rb.select(b);W.ca="name"==b;W.Da="hex"==b;W.Za="rgb"==b;W.ca&&null!=W.ta?W.ed(W.ta):null!=W.$a&&W.T(W.$a.O,W.$a.u,W.$a.G)},mh:function(){W.Ob("rgb")},
lh:function(){W.Ob("name")},kh:function(){W.Ob("hex")},sg:function(b){W.ta=null;W.Nb();W.T(b,W.za.j(),W.o.j())},rg:function(b){W.ta=null;W.Nb();W.T(W.Aa.j(),b,W.o.j())},pg:function(b){W.ta=null;W.Nb();W.T(W.Aa.j(),W.za.j(),b)},Mf:function(b){try{W.ed(G(b.target))}catch(c){alert(c)}},Qf:function(b){b=G(b.target);W.ta=null;W.Nb();W.T(parseInt(Ja(b).substring(0,2),16),parseInt(Ja(b).substring(2,4),16),parseInt(Ja(b).substring(4,6),16))},Pf:function(b){W.name.firstChild.data=G(b.target);C(b.target,"black")},
Nf:function(b){W.name.firstChild.data="";C(b.target,"none")},qg:function(b){W.Ob(b)},ib:function(b){try{null!=W.dd&&W.dd(G(b.target))}catch(c){alert("svgctrl.ColorChooser.onSelect:"+c)}},ig:function(b){W.cd.onclick(b)},Ef:function(b){W.hc.onclick(b)},ff:function(b){W.Xb.onclick(b)},Rf:function(b){Ua(W.Aa,b)},Df:function(b){Ua(W.za,b)},df:function(b){Ua(W.o,b)},Pc:function(b){W.af.Pc(b)}};window.svgctrl_ColorChooser_onOver=W.Pf;window.svgctrl_ColorChooser_onOut=W.Nf;
window.svgctrl_ColorChooser_onNameDown=W.Mf;window.svgctrl_ColorChooser_onRGBDown=W.Qf;window.svgctrl_ColorChooser_onRfClick=W.ig;window.svgctrl_ColorChooser_onGfClick=W.Ef;window.svgctrl_ColorChooser_onBfClick=W.ff;window.svgctrl_ColorChooser_onRIndexDown=W.Rf;window.svgctrl_ColorChooser_onGIndexDown=W.Df;window.svgctrl_ColorChooser_onBIndexDown=W.df;window.svgctrl_ColorChooser_onSetFormat=W.qg;window.svgctrl_ColorChooser_onStartMoving=W.Pc;window.svgctrl_ColorChooser_onSelect=W.ib;
window.svgctrl_ColorChooser_onClose=W.gf;function rb(){this.c=[];this.selected=-1;this.yb=this.r=!0;this.pa=this.hb.bind(this)}
rb.prototype.i=function(b,c){this.Q=M(b+"-box");this.Je=document.getElementById(b+"-wheel-left");this.Ie=document.getElementById(b+"-wheel-bottom");this.root=V(this.Q);this.zg=this.root.createSVGMatrix().rotate(0);this.Ag=this.root.createSVGMatrix().rotate(90);this.Bg=this.root.createSVGMatrix().scale(0);this.Cg=this.root.createSVGMatrix().scale(1);this.c=[];this.selected=-1;for(var d=0;d<c.length;d++){var k=c[d],n=M(k+"-panel-rect"),r=M(k+"-panel-clip"),y=O(r,"rect"),u=M(k+"-panel"),A=O(O(u,"g"),
"use"),N=M(k+"-panel-box"),P=O(M(k+"-panel-icon"),"use");this.c.push({Pa:u,ya:O(u,"animate"),Ye:M(k+"-header"),ld:A,Xa:O(A,"animateTransform"),clip:r,ua:y,Ga:O(y,"animate"),Q:N,Fa:O(N,"animate"),mc:P,Ka:O(P,"animateTransform"),rect:n,kc:K(n),y:L(u)})}k=this.Q.getBBox();for(d=0;d<c.length;d++)q(t(x(this.c[d].Ye,0),k.x),k.width),p(this.c[d].ua,0);this.yb=void 0!=typeof this.c[0].ya.beginElementAt?!0:!1;!0==this.r&&!1==this.yb&&(this.r=!1);null!=this.Je&&Ma(this.Je,this.pa);null!=this.Ie&&Ma(this.Ie,
this.pa);return this};function sb(b){var c=b.cloneNode(!0);b.parentNode.removeChild(b);return c}
function tb(){var b=ub;b.r=!b.r;!0==b.r&&!1==b.yb&&(b.r=!1);if(!1==b.r){!0==b.yb&&b.root.pauseAnimations();for(var c=0;c<b.c.length;c++)b.c[c].ya=sb(b.c[c].ya),b.c[c].Xa=sb(b.c[c].Xa),b.c[c].Ga=sb(b.c[c].Ga),b.c[c].Fa=sb(b.c[c].Fa),b.c[c].Ka=sb(b.c[c].Ka)}else for(b.root.unpauseAnimations(),c=0;c<b.c.length;c++)b.c[c].ya=b.c[c].Pa.appendChild(b.c[c].ya),b.c[c].Xa=b.c[c].ld.appendChild(b.c[c].Xa),b.c[c].Ga=b.c[c].ua.appendChild(b.c[c].Ga),b.c[c].Fa=b.c[c].Q.appendChild(b.c[c].Fa),b.c[c].Ka=b.c[c].mc.appendChild(b.c[c].Ka);
return b.r}function vb(b){var c=ub;b==c.selected?c.close(b):-1!=c.selected?(c.close(c.selected),!0==c.r?window.setTimeout(function(){wb(c,b)},400):xb(c,b)):c.open(b)}function xb(b,c){var d=b.selected;if(c!=d){var k=b.c[c].kc;-1!=d&&yb(b,d);b.selected=c;Fa(b.c[c].ld,b.Ag);for(d=c+1;d<b.c.length;d++)b.c[d].Pa.y.baseVal.value=b.c[d].y+k;b.c[c].ua.height.baseVal.value=k;b.c[c].Q.height.baseVal.value=k+1;Fa(b.c[c].mc,b.Bg)}}
function wb(b,c){var d=b.selected;if(c!=d){var k=0,n=b.c[c].kc;-1!=d&&(k+=zb(b,d));b.selected=c;ea(B(oa(b.c[c].Xa,90),0),"0.5s").beginElementAt(k);if(c+1<b.c.length){for(d=c+1;d<b.c.length;d++){var r=b.c[d].y;ea(oa(B(b.c[d].ya,r),r+n),"0.2s").beginElementAt(k)}k+=0.2}ea(B(oa(b.c[c].Ga,n),0),"0.5s").beginElementAt(k);ea(B(oa(b.c[c].Fa,n+1),0),"0.5s").beginElementAt(k);ea(B(oa(b.c[c].Ka,0),1),"0.5s").beginElementAt(k)}}rb.prototype.open=function(b){!0==this.r?wb(this,b):xb(this,b)};
function yb(b,c){if(c==b.selected){b.selected=-1;Fa(b.c[c].ld,b.zg);b.c[c].ua.height.baseVal.value=0;b.c[c].Q.height.baseVal.value=0;Fa(b.c[c].mc,b.Cg);for(var d=c+1;d<b.c.length;d++)b.c[d].Pa.y.baseVal.value=b.c[d].y}}
function zb(b,c){if(c==b.selected){var d=b.c[c].kc;b.selected=-1;ea(B(oa(b.c[c].Xa,0),90),"0.5s").beginElement();ea(oa(B(b.c[c].Ga,d),0),"0.2s").beginElement();ea(B(oa(b.c[c].Fa,0),d+1),"0.2s").beginElement();ea(oa(B(b.c[c].Ka,0),1),"0.2s").beginElement();for(var k=c+1;k<b.c.length;k++){var n=b.c[k].y;ea(B(oa(b.c[k].ya,n),n+d),"0.2s").beginElementAt(0.4)}return 0.6}return 0}rb.prototype.close=function(b){!0==this.r?zb(this,b):yb(this,b)};
rb.prototype.hb=function(b){b.stopPropagation();var c=this.selected;switch(Na(b)){case 1:c=0>c?0:(c-1+this.c.length)%this.c.length;break;case -1:c=(c+1+this.c.length)%this.c.length}this.open(Math.max(0,Math.min(c,this.c.length-1)))};DropTextRightCtrl=function(b,c){this.r=!0;this.W=c;this.value=M(b);this.kb=O(M(b+"-clip"),"rect");this.u=z(this.value.nextSibling,"g");this.O=O(this.u,"rect");this.k=[];for(var d=this.value.getBBox().width/8,k=this.O.nextSibling.firstChild,n=F(this.value,"x"),r=L(this.value);null!=k;k=k.nextSibling)k.tagName&&"text"==k.tagName&&(s(t(k,n),r),k.firstChild.data==this.value.firstChild.data&&T(k,"1"),n-=k.getBBox().width+d,this.k.push(k));this.G=z(this.O,"g").getBBox();ha(this.O,this.G,1);ha(z(this.value,
"rect"),this.value.getBBox(),0);void 0==typeof this.kb.firstChild.beginElement&&(this.r=!1)};DropTextRightCtrl.prototype.g=function(b){this.value.firstChild.data=b;for(var c=0;c<this.k.length;c++)this.k[c].firstChild.data==b?T(this.k[c],"1"):T(this.k[c],"0")};function Ab(b){Q(b.u);!0==b.r?B(oa(b.kb.firstChild,b.G.x-1),b.G.x+b.G.width).beginElement():t(b.kb,b.G.x-1)}
function Bb(b,c){b.W(c.target.firstChild.data);!0==b.r?B(oa(b.kb.firstChild,b.G.x+b.G.width+10),b.G.x-1).beginElement():t(b.kb,b.G.x+b.G.width+10)}
StrokeWidthBarCtrl=function(b,c){this.parent=c;this.rect=M(b+"-rect");this.b=M(b+"-bar");this.index=M(b+"-index");this.C=M(b+"-plume");this.value=M(b+"-value");this.w=M(b+"-unit");this.ic=M(b+"-gl");this.jc=M(b+"-gr");this.h=V(this.rect).createSVGLength();this.nd={num:1,px:5,cm:6,mm:7,"in":8,pt:9,pc:10};this.ub="     px cm mm in pt pc".split(" ");this.k=[];this.O=[];this.t=[];this.K=0;this.U=1;this.ja=this.K+10*this.U;this.qd=F(this.b,"x2")-F(this.b,"x1");this.A="";this.F=1;this.V=new DropTextRightCtrl(h(this.w),
this.Nc.bind(this));this.n=(new Sa).i(b,!0,this.K,this.ja,1,this.wa.bind(this),null);R(this.b)};e=StrokeWidthBarCtrl.prototype;e.Ha="1px";e.A="px";e.F=5;e.N=function(){return S(this.C)};e.na=function(){!1==this.N()&&this.Ta(this.Ha)};
e.f=function(){for(var b=V(this.rect),c=0,d=this.jc.firstChild,k=this.ic.firstChild,n=K(this.rect),r=L(this.rect),y=F(this.b,"x1"),u=(F(this.b,"x2")-y)/10,A=F(this.b,"y1"),N=this.K+this.U;10>c;c++){var P=b.createSVGLength();P.valueAsString=N+"px";this.k.push(pa(D(g(k,"d","M "+y+" "+A+"h"+u),N+"px")));this.O.push(D(t(s(q(p(d,n),u),r),y),N+"px"));this.t.push(P);y+=u;N+=this.U;d=d.nextSibling;k=k.nextSibling}this.tb()};e.Ra=function(b){C(this.ic,b)};e.gc=function(){return J(this.b)};
e.Ta=function(b){try{if(this.A="",this.F=1,this.h.valueAsString=b,4<this.h.unitType&&11>this.h.unitType){var c=this.h.valueInSpecifiedUnits.toFixed(this.va);this.h.unitType!=this.F&&this.pb(this.ub[this.h.unitType]);this.g(c);Q(this.w)}else D(this.b,this.h.valueAsString),this.value.firstChild.data=this.h.valueAsString,Ta(this.n),Q(this.C),1==this.h.unitType?(this.A="",this.F=1,this.V.g("xy"),Q(this.w)):R(this.w)}catch(d){}return J(this.b)};e.nb=function(){ca(this.b);this.n.D(!1);R(this.C);R(this.w)};
e.fc=function(){this.h.valueAsString=J(this.b);return this.h.valueInSpecifiedUnits};e.hd=function(b){var c=J(this.b);if(null!=c)try{this.h.valueAsString=c,this.h.convertToSpecifiedUnits(b),D(this.b,this.h.valueAsString)}catch(d){}};
e.tb=function(){this.s=Da(V(this.rect));this.ja=this.t[this.k.length-1].valueInSpecifiedUnits;this.U=this.t[1].valueInSpecifiedUnits-this.t[0].valueInSpecifiedUnits;this.K=this.t[0].valueInSpecifiedUnits-this.U;this.qc=(this.ja-this.K)*this.s/this.qd;this.va=1;for(var b=0.1;b>this.qc;b/=10)this.va++;this.n.setInterval(this.K,this.ja,this.va)};
e.pb=function(b){try{this.A="";this.F=1;if(-1!="px,cm,mm,in,pt,pc".indexOf(b)){for(var c=this.F,d=this.nd[b],k=0;k<this.k.length;k++){var n=k;try{this.t[n].convertToSpecifiedUnits(d),D(this.k[n],this.t[n].valueAsString),D(this.O[n],this.t[n].valueAsString)}catch(r){}}this.hd(d);this.h.valueAsString=this.Ha;try{this.h.convertToSpecifiedUnits(d),this.Ha=this.h.valueAsString}catch(y){}this.A=this.ub[d];this.F=d;this.N()&&(this.value.firstChild.data=this.fc().toFixed(2));1==c&&this.n.g(parseFloat(this.value.firstChild.data));
this.V.g(b);this.tb();Q(this.w);return!0}if("xy"==b||""==b)this.A="",this.F=1,this.V.g("xy"),Ta(this.n),D(this.b,this.j()),Q(this.w);return!1}catch(u){}};e.j=function(){return this.n.j()};e.g=function(b){D(this.b,b+this.A);this.n.g(b);Q(this.C);this.Ha=J(this.b)};e.$=function(){S(this.C)?this.parent.fg():this.parent.Gb(this.Ha)};e.Nc=function(b){this.pb(b);this.parent.Gb(this.gc())};e.wa=function(b){this.parent.Gb(b+this.A)};
OpacityBarCtrl=function(b,c){this.l=M(b+"-bar");this.C=M(b+"-plume");this.parent=c;this.Bb=1;this.n=(new Sa).i(b,!0,1,0,2,this.wa.bind(this),null)};e=OpacityBarCtrl.prototype;e.N=function(){return S(this.C)};e.na=function(){!1==this.N()&&this.ga(this.Bb)};e.ga=function(b){this.n.g(b);this.Bb=b;Q(this.C)};e.S=function(){this.n.D(!1);R(this.C)};e.ba=function(b){l(this.l,b)};e.$=function(){null==this.parent.Rd()?this.parent.Oa(this.Bb):this.parent.de()};
e.I=function(b){this.parent.Oa(parseFloat(H(b.target,"fill-opacity")))};e.wa=function(b){this.parent.Oa(parseFloat(b))};VerticalTab=function(b){this.name=b;this.Q=document.getElementById(this.name+"-box");this.ua=O(M(b+"-clip"),"rect");this.e=M(b+"-area");this.Wa=O(M(b+"-tab"),"rect");this.Va=z(this.Wa,"rect");this.lc=null!=this.Q?K(this.Q):this.e.getBBox().height;this.cb=K(this.ua);this.scale=this.lc/this.cb;this.oc=null;this.$b=0;this.pa=this.hb.bind(this);null!=this.Q&&Ma(this.Q,this.pa)};
VerticalTab.prototype.f=function(){var b=z(this.Va,"g"),c=z(b,"g"),d=[],k=L(this.ua),n=F(this.Wa,"width"),r=F(this.Wa,"x"),y=0,u=0;this.oc=[];for(var A=this.e.firstChild;null!=A;A=A.nextSibling)if(A.tagName&&"g"==A.tagName){var N=h(A);if(null!=N){var P=M(N+"-title").firstChild.data;d.push(P);this.oc.push(P.length);u+=P.length;y++}}s(p(this.Va,this.cb*this.cb/this.lc),k);p(s(this.Wa,k),this.cb);Ma(b,this.pa);for(A=0;A<y;A++){var N=this.oc[A]*this.cb/u,P=d[A],La=va(c,"text");va(La,"tspan").appendChild(document.createTextNode(P));
P=E(s(t(La,0),0),"translate("+(r+n-n/4)+" "+(k+N/2)+") rotate(-90)");da(P,"unselect");da(P.firstChild,"unselect");var P=r,La=k,Gc=n,Hc=N;t(s(q(p(va(b,"rect"),Hc),Gc),La),P);k+=N}this.Z=L(this.Wa);this.fb=this.Z+K(this.Wa)-K(this.Va);this.$b=this.Z};VerticalTab.prototype.scrollTo=function(b){b=Math.max(this.Z,Math.min(this.fb,b));E(this.e,"translate(0 "+(this.Z-b)*this.scale+")");E(this.Va,"translate(0 "+(b-L(this.Va))+")");this.$b=b};
VerticalTab.prototype.I=function(b){this.scrollTo(L(b.target)+K(b.target)/2-K(this.Va)/2)};VerticalTab.prototype.hb=function(b){b.stopPropagation();this.scrollTo(-Na(b)*this.lc/10+this.$b)};FontFamilyCtrl=function(b,c){this.parent=c;this.od=M(b+"-value");this.Vc=M(b+"-plume");this.cc="serif";this.m=(new ib).i(b,this.ib.bind(this),!1)};e=FontFamilyCtrl.prototype;e.ib=function(b){this.parent.Kc(H(b,"font-family"))};e.aa=function(b){Q(this.Vc);Q(this.od);this.m.g(b);this.cc=this.od.firstChild.data=b};
e.lb=function(){R(this.Vc);R(this.od);this.m.P()};e.N=function(){return S(this.Vc)};e.na=function(){!1==this.N()&&this.aa(this.cc)};e.$=function(){this.N()?this.parent.Wf():this.parent.Kc(this.cc)};e.ra=function(){this.m.ra()};e.qa=function(){this.m.qa()};e.Pd=function(b){return this.m.findText(b)};
FontSizeBarCtrl=function(b,c){this.parent=c;this.b=M(b+"-bar");this.index=M(b+"-index");this.C=M(b+"-plume");this.value=M(b+"-value");this.w=M(b+"-unit");this.Td=M(b+"-gt");this.jc=M(b+"-gr");this.h=V(this.b).createSVGLength();this.nd={num:1,px:5,cm:6,mm:7,"in":8,pt:9,pc:10};this.ub="     px cm mm in pt pc".split(" ");this.k=[];this.jd=[];this.O=[];this.t=[];this.U=this.K=4;this.ja=this.K+10*this.U;this.A="px";this.F=5;this.qd=F(this.b,"x2")-F(this.b,"x1");this.X=V(this.b).createSVGLength();this.X.valueAsString=
"20px";this.V=new DropTextRightCtrl(h(this.w),this.Nc.bind(this));this.n=(new Sa).i(b,!0,this.K,this.ja,1,this.wa.bind(this),null);R(this.b)};e=FontSizeBarCtrl.prototype;
e.f=function(){var b=V(this.b);this.s=Da(b);for(var c=0,d=this.jc.firstChild,k=this.Td.firstChild,n=F(this.b,"x1"),r=(F(this.b,"x2")-n)/10,y=F(this.b,"y1"),u=this.K+this.U;10>c;c++){var A=b.createSVGLength();A.valueAsString=u+"px";this.jd.push(ma(s(t(k,n),y),u*this.s+"px"));this.O.push(D(q(t(ha(d,k.getBBox(),0),n),r),u+"px"));this.t.push(A);n+=r;u+=this.U;d=d.nextSibling;k=k.nextSibling}this.tb()};e.$=function(){try{this.N()?this.parent.$f():this.parent.jb(this.X.valueAsString)}catch(b){alert(b)}};
e.I=function(b){try{this.X.valueAsString=J(b.target),this.parent.jb(this.X.valueAsString)}catch(c){alert(c)}};e.wa=function(b){this.X.valueInSpecifiedUnits=b;this.parent.jb(this.X.valueAsString)};e.aa=function(b){la(this.Td,b)};e.Ra=function(b){C(this.ic,b)};e.Sd=function(){return J(this.b)};e.N=function(){return null!=J(this.b)};e.j=function(){this.h.valueAsString=J(this.b);return this.h.valueInSpecifiedUnits};
e.Sa=function(b){try{if(this.h.valueAsString=b,4<this.h.unitType&&11>this.h.unitType){var c=this.h.valueInSpecifiedUnits.toFixed(this.va);this.h.unitType!=this.F&&this.pb(this.ub[this.h.unitType]);this.g(c);Q(this.w)}else D(this.b,this.h.valueAsString),this.value.firstChild.data=this.h.valueAsString,Ta(this.n),Q(this.C),1==this.h.unitType?(this.A="",this.F=1,this.V.g("xy"),Q(this.w)):R(this.w)}catch(d){}return J(this.b)};e.mb=function(){ca(this.b);this.n.D(!1);R(this.C);R(this.w)};
e.fc=function(){this.h.valueAsString=J(this.b);return this.h.valueInSpecifiedUnits};e.hd=function(b){var c=J(this.b);if(null!=c){this.h.valueAsString=c;try{this.h.convertToSpecifiedUnits(b),D(this.b,this.h.valueAsString)}catch(d){}}};
e.tb=function(){this.K=this.t[0].valueInSpecifiedUnits;this.U=this.t[1].valueInSpecifiedUnits-this.t[0].valueInSpecifiedUnits;this.ja=this.t[this.jd.length-1].valueInSpecifiedUnits+this.U;this.qc=(this.ja-this.K)*this.s/this.qd;this.va=1;for(var b=0.1;b>this.qc;b/=10)this.va++;this.n.setInterval(this.K,this.ja,this.va)};
e.pb=function(b){try{if(-1!="px,cm,mm,in,pt,pc".indexOf(b)){for(var c=this.F,d=this.nd[b],k=0;k<this.jd.length;k++){var n=k;try{this.t[n].convertToSpecifiedUnits(d),D(this.O[n],this.t[n].valueAsString)}catch(r){}}this.hd(d);this.h.valueAsString=this.X.valueAsString;try{this.h.convertToSpecifiedUnits(d),this.X.convertToSpecifiedUnits(d)}catch(y){}this.A=this.ub[d];this.F=d;this.N()&&(this.value.firstChild.data=this.fc().toFixed(2));1==c&&this.n.g(parseFloat(this.value.firstChild.data));this.V.g(b);
this.tb();Q(this.w);return!0}if("xy"==b||""==b)this.A="",this.F=1,this.V.g("xy"),Ta(this.n),D(this.b,this.j()),Q(this.w);return!1}catch(u){}};e.g=function(b){D(this.b,b+this.A);this.n.g(b);Q(this.C);this.X.valueAsString=J(this.b)};e.Nc=function(b){this.pb(b);this.parent.jb(this.Sd())};e.N=function(){return S(this.C)};e.na=function(){!1==this.N()&&this.Sa(this.X.valueAsString)};
FontWeightCtrl=function(b,c){this.parent=c;this.kd=M(b+"-text");this.td=M(b+"-value");this.se=M(b+"-plume");this.Md="normal";this.m=(new ib).i(b,this.ib.bind(this),!1)};e=FontWeightCtrl.prototype;e.ib=function(b){this.parent.ne(H(b,"font-weight"))};e.aa=function(b){la(this.kd,b)};e.Qb=function(b){this.m.g(b);m(this.kd,"font-weight",b);Q(this.se);Q(this.td);this.Md=this.td.firstChild.data=b};e.Qa=function(){this.m.P();f(this.kd,"font-weight");R(this.se);R(this.td)};
e.$=function(){try{null==this.parent.Xe()?this.parent.ne(this.Md):this.parent.hg()}catch(b){alert(b)}};e.ra=function(){this.m.ra()};e.qa=function(){this.m.qa()};e.Qd=function(b){return this.m.findText(b)};e.f=function(){this.m.f()};window.mnuInit=function(b){var c="";try{x(M("stroke-header"),0);x(M("fill-header"),0);c="mo.init";Cb="new open save print png pty resize grid butterfly lion tiger toucan mapmonde villandry".split(" ");p(M("doc-panel-clip").firstChild,K(M("doc-panel-rect")));Db=new VerticalTab("doc");Db.f();for(var d=0;d<Cb.length;d++)ia(O(M("doc-"+Cb[d]+"-tip"),"text"),1);c="ml.init";Eb=["select","applystyle","front","back","def-marker"];p(M("sel-panel-clip").firstChild,K(M("sel-panel-rect")));Fb=(new ib).i("sel-ld",
Gb,!0);Hb=new VerticalTab("sel");Hb.f();for(d=0;d<Eb.length;d++)ia(O(M("sel-"+Eb[d]+"-tip"),"text"),1);c="mt.init";X.f(b);c="mf.init";Y.f(b);c="ms.init";I.f(b);c="md.init";p(M("dbasic-panel-clip").firstChild,K(M("dbasic-panel-rect")));Ib="text line polyline rect circle ellipse polygon image map svg circlearc path freepath cubicarc cubiccurve cubicclosedcurve cubicsmoothcurve cubicsmoothclosedcurve quadarc quadcurve quadclosedcurve quadsmoothcurve quadsmoothclosedcurve".split(" ");for(b=0;b<Ib.length;b++)ia(O(M("dbasic-"+
Ib[b]+"-tip"),"text"),1);Jb=null;Kb=new VerticalTab("task");Kb.f();c="mshape.init";p(M("shape-panel-clip").firstChild,K(M("shape-panel-rect")));Lb=(new cb).i("shape-arrows",!0);Mb=(new cb).i("shape-flowcharts",!0);Nb=null;Ob=new VerticalTab("shape");Ob.f();c="mm.init";ub=(new rb).i("mnu-ac","doc sel dbasic shape stroke fill font marker option".split(" "));c="mk.init";Pb=M("marker-start-area");Qb=M("marker-mid-area");Rb=M("marker-end-area");Sb=M("line-marker");Tb=M("plume-marker-start");Ub=M("v-marker-start");
Vb=null;Wb=M("plume-marker-mid");Xb=M("v-marker-mid");Yb=null;Zb=M("plume-marker-end");$b=M("v-marker-end");ac=null;bc=(new cb).i("marker-start",!0);cc=(new cb).i("marker-mid",!0);dc=(new cb).i("marker-end",!0);ec=fc=h(M("circle8"));gc=h(M("arrow20-16-right"));x(M("markerEndToolBtn"),1);x(M("markerMidToolBtn"),1);x(M("markerStartToolBtn"),1);ia(O(M("markerEndTool-tip"),"text"),1);ia(O(M("markerMidTool-tip"),"text"),1);ia(O(M("markerStartTool-tip"),"text"),1);hc=new VerticalTab("marker");hc.f();ic();
c="mopt.init";jc=(new Va).i("animate-option");kc=(new Va).i("svg1-2-option");jc.g(ub.r);kc.g(I.ha);W.f();alert("mnuInit done")}catch(k){alert("mnuInit("+c+"): "+k)}};function lc(b){var c=h(b),c=document.getElementById(c);null==c?(M("gradients").appendChild(document.importNode(b,!0)),"undefined"!=typeof I&&(I.eb(),db(I.p)),"undefined"!=typeof Y&&(Y.eb(),db(Y.p))):(c.parentNode.removeChild(c),M("gradients").appendChild(document.importNode(b,!0)))}
function mc(b){var c=h(b),c=document.getElementById(c);null==c?(M("markers").appendChild(document.importNode(b,!0)),"undefined"!=typeof nc&&ic()):(c.parentNode.removeChild(c),M("markers").appendChild(document.importNode(b,!0)))}function oc(b){za(b);for(var c=0,d=0,k=M("gradients").firstChild;null!=k;k=k.nextSibling)if("linearGradient"==k.tagName||"radialGradient"==k.tagName)44==c&&(c=0,d+=7),G(fa(q(p(s(t(va(b,"rect"),c),d),6),10),h(k))),c+=11}
function pc(b,c){for(var d=b.firstChild;null!=d;d=d.nextSibling)if(sa(G(d))==c)return d;return null}function Z(b){if(Pa(b))window.parent[b]()}function $(b,c){if(Pa(b))window.parent[b](c)}window.mnu_ma_onClick=function(b){b.stopPropagation();b.preventDefault()};window.mnu_ma_show=function(b){Q(M(b))};window.mnu_ma_hide=function(b){R(M(b))};try{window.menu={open:function(b){try{ub.open(b)}catch(c){alert("mm.open("+b+") "+c)}}},window.parent.menu=window.menu}catch(qc){}var ub;
window.mnu_mm_invert=function(b){try{vb(b)}catch(c){alert("mm.invert("+b+") "+c)}};try{window.doc={setTaskState:function(b,c){!0==c?(C(O(M(b),"rect"),"sienna"),rc=b):(C(O(M(b),"rect"),"none"),rc=null)}},window.parent.doc=window.doc}catch(sc){}var Cb,Db,rc;window.mnu_mo_onOverTask=function(b){Q(M(b.target.parentNode.id+"-tip"));C(b.target,"sienna")};window.mnu_mo_onOutTask=function(b){var c=b.target.parentNode.id;R(M(c+"-tip"));c!=rc&&C(b.target,"none")};
window.mnu_mo_onDownTask=function(b){$("onStartTask",b.target.parentNode.id)};window.mnu_mo_onNew=function(){Z("onNewDocument")};window.mnu_mo_onPty=function(){Z("onPtyDocument")};window.mnu_mo_onResize=function(){Z("onResizeDocument")};window.mnu_mo_onGrid=function(){Z("onGridDocument")};window.mnu_mo_onOpen=function(){Z("onOpenDocument")};window.mnu_mo_onSave=function(){Z("onSaveDocument")};window.mnu_mo_onPrint=function(){Z("onPrintDocument")};window.mnu_mo_onPNG=function(){Z("onExportDocumentPNG")};
window.mnu_mo_onSample=function(b){$("onSampleDocument",b)};window.mnu_mo_vtOnRectDown=function(b){Db.I(b)};
try{window.sel={setTaskState:function(b,c){!0==c?(C(O(M(b),"rect"),"sienna"),tc=b):(C(O(M(b),"rect"),"none"),tc=null)},setTaskEnabled:function(b,c){!0==c?T(O(M(b),"rect"),"E"):(T(O(M(b),"rect"),"D"),R(M(b+"-tip")))},addDrawn:function(b){var c=Fb,d;a:{for(d=c.e.firstChild;null!=d;d=d.nextSibling)if(d.tagName&&"g"==d.tagName)break a;d=null}var k=M(c.name+"-gmodel").cloneNode(!0);O(k,"text").firstChild.data=b;k.id=null;d?c.e.insertBefore(k,d):c.e.appendChild(k);jb(c)},removeDrawn:function(b){Fb.removeNode(b)},
changeDrawn:function(b,c){var d=mb(Fb,b);null!=d&&(O(d,"text").firstChild.data=c)},selectDrawn:function(b){Fb.g(b)}},window.parent.sel=window.sel}catch(uc){}function vc(b){return-1!=qa(b.target).indexOf("E")}function Gb(b,c){if(Pa("onDrawnSelect"))window.parent.onDrawnSelect(b.firstChild.data,c)}var Eb,Fb,Hb,tc;window.mnu_ml_onOverTask=function(b){Q(M(b.target.parentNode.id+"-tip"));C(b.target,"sienna")};
window.mnu_ml_onOutTask=function(b){var c=b.target.parentNode.id;R(M(c+"-tip"));c!=tc&&C(b.target,"none")};window.mnu_ml_onOverTaskE=function(b){vc(b)&&(Q(M(b.target.parentNode.id+"-tip")),C(b.target,"sienna"))};window.mnu_ml_onOutTaskE=function(b){var c=b.target.parentNode.id;R(M(c+"-tip"));c!=tc&&C(b.target,"none")};window.mnu_ml_onDownTask=function(b){$("onStartTask",b.target.parentNode.id)};window.mnu_ml_onSelect=function(){Z("onSelectElement")};window.mnu_ml_onApplyStyle=function(){Z("onApplyStyle")};
window.mnu_ml_onFront=function(b){vc(b)&&Z("onSelectFront")};window.mnu_ml_onBack=function(b){vc(b)&&Z("onSelectBack")};window.mnu_ml_onDefMarker=function(b){vc(b)&&Z("onDefMarker")};window.mnu_ml_vtOnRectDown=function(b){Hb.I(b)};window.mnu_ml_onLdNextRectDown=function(b){nb(Fb,b)};window.mnu_ml_onLdNextRectOver=function(b){ob(b)};window.mnu_ml_onLdNextRectOut=function(b){qb(b)};window.mnu_ml_onLdBarUp=function(){eb(Fb.B)};window.mnu_ml_onLdBarBottom=function(){fb(Fb.B)};
window.mnu_ml_onLdBarBackDown=function(b){gb(Fb.B,b)};window.mnu_ml_onLdBarDown=function(b){hb(Fb.B,b)};try{window.dbasic={setTaskState:function(b,c){!0==c?(C(O(M(b),"rect"),"sienna"),Jb=b):(C(O(M(b),"rect"),"none"),Jb=null)}},window.parent.dbasic=window.dbasic}catch(wc){}var Ib,Jb,Kb;window.mnu_md_onOverTask=function(b){Q(M(b.target.parentNode.id+"-tip"));C(b.target,"sienna")};window.mnu_md_onOutTask=function(b){var c=b.target.parentNode.id;R(M(c+"-tip"));c!=Jb&&C(b.target,"none")};
window.mnu_md_onDownTask=function(b){$("onStartTask",b.target.parentNode.id)};window.mnu_md_vtOnRectDown=function(b){Kb.I(b)};try{window.shape={disableShapeTask:function(){xc()}},window.parent.shape=window.shape}catch(yc){}function xc(){null!=Nb&&(T(z(Nb,"rect"),"0"),T(Nb,"0"),Nb=null)}function zc(b){return"rect"==b.target.tagName?b.target.previousSibling:b.target}var Lb,Mb,Nb,Ob;window.mnu_mshape_onOverShape=function(b){T(zc(b),"1")};window.mnu_mshape_onOutShape=function(b){b=zc(b);b!=Nb&&T(b,"0")};
window.mnu_mshape_onShapeDown=function(b){b=zc(b);b!=Nb&&(xc(),T(z(b,"rect"),"1"),Nb=b,$("onStartShapeTask",b))};window.mnu_mshape_vtOnRectDown=function(b){Ob.I(b)};window.mnu_mshape_bArrows_onUp=function(){eb(Lb)};window.mnu_mshape_bArrows_onBottom=function(){fb(Lb)};window.mnu_mshape_bArrows_onBarBackDown=function(b){gb(Lb,b)};window.mnu_mshape_bArrows_onBarDown=function(b){hb(Lb,b)};window.mnu_mshape_bFlowcharts_onUp=function(){eb(Mb)};window.mnu_mshape_bFlowcharts_onBottom=function(){fb(Mb)};
window.mnu_mshape_bFlowcharts_onBarBackDown=function(b){gb(Mb,b)};window.mnu_mshape_bFlowcharts_onBarDown=function(b){hb(Mb,b)};
try{window.stroke={clear:function(){I.clear()},setEnabled:function(b,c){I.D(b);"undefined"!=typeof X&&X.D(c)},setScaling:function(b){I.gd(b)},setColor:function(b,c){!0==b?"none"==c?I.J(!0):(I.R()&&I.J(!1),I.Pb(c)):(I.R()&&I.J(!1),I.Kb())},setDash:function(b,c){!0==b?I.fd(c):I.Yc()},setDashOffset:function(b,c){!0==b?I.Dg(c):I.xg()},setLinecap:function(b,c){!0==b?I.xe(c):I.ad()},setLinejoin:function(b,c){!0==b?I.ye(c):I.bd()},setWidth:function(b,c){!0==b?I.Ta(c):I.nb()},setOpacity:function(b,c){!0==
b?I.ga(c):I.S()},setMiterLimit:function(b,c){!0==b?I.Eg(c):I.yg()},setGrd:function(b,c){!0==b?(lc(c),I.R()&&I.J(!1),I.ob(h(c))):(I.R()&&I.J(!1),I.fa())},setSvg12Enabled:function(b){I.ha=!0==b?!0:!1;"undefined"!=typeof Ac&&kc.g(I.ha)}},window.parent.stroke=window.stroke}catch(Bc){}
var I={ha:!0,f:function(){p(M("stroke-panel-clip").firstChild,K(M("stroke-panel-rect")));I.Cb="sienna";I.Ha="1px";I.bc="4px, 4px";I.Jd="butt";I.Kd="miter";I.rd=M("v-stroke");I.Ib=M("plume-stroke");I.Hg=M("t-stroke-db");I.te=M("pen-stroke-color");I.yd=M("arrow-stroke-color");I.b=M("line-stroke");I.Ua=(new Xa).f(I.rd,I.Zb);Ya(I.Ua,"Sienna");I.He=(new Xa).f(M("stroke-width-value"),I.Ng);Ya(I.He,"10.00");I.ac=(new Xa).f(M("v-stroke-dasharray"),I.Me);Ya(I.ac,"4px, 4px, 8px, 4px");I.gb=(new Xa).f(M("stroke-opacity-value"),
I.Qc);Ya(I.gb,"0.01");I.Vd=M("gl-stroke-dasharray");I.Ge=M("v-stroke-dasharray");I.Tc=M("plume-stroke-dash");I.Xg=M("stroke-width-index");I.ph=M("stroke-width-value");I.eh=M("stroke-width-plume");I.md=(new Va).i("vector-effect");I.L=new StrokeWidthBarCtrl("stroke-width",I);I.L.f();I.ia=M("v-stroke-grd");I.xa=M("plume-stroke-grd");I.v=null;I.p=(new cb).i("stroke-grd");I.eb();db(I.p);I.sb=(new Va).i("stroke-none");I.q=new OpacityBarCtrl("stroke-opacity",I);I.De=(new Wa).i("stroke-linecap-group");I.oe=
M("stroke-linecap-plume");I.Ee=(new Wa).i("stroke-linejoin-group");I.pe=M("stroke-linejoin-plume");x(M("stroke-color-title"),0);x(M("stroke-width-title"),0);x(M("stroke-dash-title"),0);x(M("stroke-gradient-title"),0);x(M("stroke-opacity-title"),0);x(M("stroke-width-unit"),0);x(M("strokeGrdToolBtn"),1);ia(O(M("strokeGrdTool-tip"),"text"),1);I.sa=new VerticalTab("stroke");I.sa.f();I.Pb("sienna");I.D(!0)},bf:function(){I.ha=!I.ha;!1==I.ha&&I.le(!0);return I.ha},Zb:function(b,c,d){return void 0!=Ka[c]||
Ia(c)||Ha(c)?(I.Fb(c),c):d},Ng:function(b,c,d){return!0==RegExp("[0-9]*( .[0-9]*)?","g").test(c)&&(b=parseFloat(c).toFixed(2),0<=b)?(I.L.g(b),I.Ta(b+I.L.A),$("onSetStrokeWidth",I.gc()),b):d},Me:function(b,c,d){return!0==RegExp("[0-9]*( .[0-9]*)?(em|ex|px|in|cm|mm|pt|pc|%)?(,[0-9]*( .[0-9]*)?(em|ex|px|in|cm|mm|pt|pc|%)?)*","g").test(c)?(I.Mc(c),c):d},Qc:function(b,c,d){return!0==RegExp("[0-1]*( .[0-9]*)?","g").test(c)&&(b=parseFloat(c).toFixed(2),0<=b&&1>=b)?(I.Oa(b),b):d},D:function(b){!0==b?R(M("stroke-disabled-rect")):
Q(M("stroke-disabled-rect"))},clear:function(){I.gd(!0);I.Kb();I.nb();I.Yc();I.fa();I.S();I.ad();I.bd()},eb:function(){oc(I.p.e);I.v=I.p.e.firstChild;I.la=sa(G(I.v))},log:function(b){I.Hg.firstChild.data=b},R:function(){return I.sb.j()},J:function(b){I.sb.g(b);Ba(M("stroke-none-rect"),b);!0==b?C(I.b,"none"):null!=I.ab()?I.nh(I.b,I.la):C(I.b,I.Cb);void 0!=I.e&&Y.isEnabled()&&C(I.e,ta())},Ud:function(){return I.md.j()},gd:function(b){I.md.g(b);b=!0==b?"scaling (svg1.1)":"non scaling (1.2)";var c=I.md;
z(c.da,"text").firstChild.data=b;ka(z(c.da,"text"))},Wg:function(){return ta()},Pb:function(b){I.fa();l(I.te,b);l(I.yd,b);C(I.b,b);C(I.Vd,b);I.L.Ra(b);I.q.ba(b);Q(I.Ib);Q(I.rd);I.Ua.g(b);I.Cb=b;void 0!=I.e&&Y.isEnabled()&&C(I.e,ta())},Kb:function(){ba(I.b);R(I.Ib);R(I.rd);void 0!=I.e&&Y.isEnabled()&&ba(I.e)},nb:function(){I.L.nb();ca(I.b)},Yc:function(){f(I.b,"stroke-dasharray");R(I.Tc);R(I.Ge);void 0!=I.e&&Y.isEnabled()&&f(I.e,"stroke-dasharray")},xg:function(){f(I.b,"stroke-dashoffset")},yg:function(){f(I.b,
"stroke-miterlimit")},S:function(){f(I.b,"stroke-opacity");I.q.S();void 0!=I.e&&Y.isEnabled()&&f(I.e,"stroke-opacity")},ab:function(){if(S(I.xa)){var b=I.ia.firstChild.data;return" "==b?null:b}return null},dc:function(b){return pc(M("stroke-grd-area"),b)},ob:function(b){null!=I.v&&ca(I.v);I.Kb();fa(I.te,b);fa(I.yd,b);var c=I.b;ba(c);g(c,"stroke","url(#"+b+")");Q(I.xa);Q(I.ia);I.ia.firstChild.data=b;I.la=b;I.v=I.dc(b);I.q.ba("sienna");I.L.Ra("sienna");C(I.Vd,"sienna");null!=I.v&&D(I.v,"0.5px")},fa:function(){ba(I.b);
R(I.xa);R(I.ia)},Ta:function(b){D(I.b,I.L.Ta(b))},gc:function(){return J(I.b)},fd:function(b){m(I.b,"stroke-dasharray",b);I.ac.g(ua(I.b));I.bc=ua(I.b);Q(I.Tc);Q(I.Ge);void 0!=I.e&&Y.isEnabled()&&(b=ua(I.b),m(I.e,"stroke-dasharray",b))},Ne:function(){!1==S(I.Tc)&&I.fd(I.bc)},Te:function(){return ua(I.b)},Dg:function(b){m(I.b,"stroke-dashoffset",b)},Qg:function(){return H(I.b,"stroke-dashoffset")},Eg:function(b){m(I.b,"stroke-miterlimit",b)},Ug:function(){return H(I.b,"stroke-miterlimit")},ga:function(b){m(I.b,
"stroke-opacity",b);I.q.ga(b);void 0!=I.e&&Y.isEnabled()&&(b=H(I.b,"stroke-opacity"),m(I.e,"stroke-opacity",b))},Rd:function(){return H(I.b,"stroke-opacity")},ad:function(){f(I.b,"stroke-linecap");var b=M("stroke-linecap-line");f(b,"stroke-linecap");I.De.P();R(I.oe)},xe:function(b){m(I.b,"stroke-linecap",b);var c=M("stroke-linecap-line");m(c,"stroke-linecap",b);I.De.select(b);I.Jd=b;Q(I.oe)},Ue:function(){return H(I.b,"stroke-linecap")},bd:function(){f(I.b,"stroke-linejoin");var b=M("stroke-linejoin-line");
f(b,"stroke-linejoin");I.Ee.P();R(I.pe)},ye:function(b){m(I.b,"stroke-linejoin",b);var c=M("stroke-linejoin-line");m(c,"stroke-linejoin",b);I.Ee.select(b);I.Kd=b;Q(I.pe)},Ve:function(){return H(I.b,"stroke-linejoin")},Pe:function(){!1==S(I.Ib)&&I.Pb(I.Cb)},Lc:function(b){I.J(b);$("onSetStroke",!0==b?"none":ta())},Fb:function(b){I.Pb(b);$("onSetStrokeColor",b)},Gb:function(b){I.Ta(b);$("onSetStrokeWidth",b)},Mc:function(b){I.fd(b);$("onSetStrokeDash",b)},ie:function(b){I.ob(b);$("onSetStrokeGrd",M(b))},
je:function(b){I.xe(b);$("onSetStrokeLinecap",b)},ke:function(b){I.ye(b);$("onSetStrokeLinejoin",b)},le:function(b){I.gd(b);$("onSetStrokeScaling",b)},Oa:function(b){I.ga(b);$("onSetStrokeOpacity",b)},ag:function(){I.Kb();Z("onRemoveStroke")},fg:function(){I.nb();Z("onRemoveStrokeWidth")},bg:function(){I.Yc();Z("onRemoveStrokeDash")},cg:function(){I.fa();Z("onRemoveStrokeGrd")},dg:function(){I.ad();Z("onRemoveStrokeLinecap")},eg:function(){I.bd();Z("onRemoveStrokeLinejoin")},de:function(){I.S();Z("onRemoveStrokeOpacity")},
Ic:function(b){I.Fb(G(b.target))},tg:function(){S(I.Ib)?I.ag():I.Fb(I.Cb)},Gf:function(b){I.Mc(ua(b.target))},hf:function(){null==I.Te()?I.Mc(I.bc):I.bg()},If:function(b){D(b.target,"5px")},Hf:function(b){D(b.target,"1px")},Tf:function(b){D(b.target.nextSibling,"5px")},Sf:function(b){D(b.target.nextSibling,"1px")},Jc:function(b){I.ie(sa(G(b.target)))},wc:function(){null==I.ab()?I.ie(I.la):I.cg()},Jf:function(){null==I.Ue()?I.je(I.Jd):I.dg()},Kf:function(){null==I.Ve()?I.ke(I.Kd):I.eg()},Gc:function(){I.Lc(!I.R())},
og:function(){!0!=I.ha&&I.Ud()||I.le(!I.Ud())},xc:function(){Z("onGrdStrokeTool")},Dc:function(){W.bb();R(M("stylepanel-disabled"))},Ec:function(b){I.Fb(b);W.bb();R(M("stylepanel-disabled"))},Cc:function(){Q(M("stylepanel-disabled"));W.show(2,L(M("stroke-panel"))+2,1.2,I.Ec,I.Dc);W.Ra(ta())},Oc:function(b){I.Pe();I.Ua.onclick(b)},vg:function(b){I.L.na();I.He.onclick(b)},jf:function(b){I.Ne();I.ac.onclick(b)},Hc:function(b){I.q.na();I.gb.onclick(b)},wb:function(b){I.sa.I(b)},Kg:function(b){var c=I.L;
try{c.parent.Gb(J(b.target))}catch(d){}},Ig:function(b){Ua(I.L.n,b)},Mg:function(){Ab(I.L.V)},Lg:function(b){Bb(I.L.V,b)},Jg:function(b){I.L.$(b)},Wb:function(){eb(I.p)},Vb:function(){fb(I.p)},Tb:function(b){gb(I.p,b)},Ub:function(b){hb(I.p,b)},tc:function(b){I.q.I(b)},rc:function(b){Ua(I.q.n,b)},sc:function(b){I.q.$(b)}};window.mnu_ms_onSfClick=I.Oc;window.mnu_ms_onWfClick=I.vg;window.mnu_ms_onDashfClick=I.jf;window.mnu_ms_onOfClick=I.Hc;window.mnu_ms_vtOnRectDown=I.wb;window.mnu_ms_onNoneDown=I.Gc;
window.mnu_ms_onRectColorDown=I.Ic;window.mnu_ms_onLut=I.Cc;window.mnu_ms_onStrokeEditDown=I.tg;window.mnu_ms_onScalingDown=I.og;window.mnu_ms_wbOnLineDown=I.Kg;window.mnu_ms_wbHsOnIndexDown=I.Ig;window.mnu_ms_wbWuOnValueDown=I.Mg;window.mnu_ms_wbWuOnTextDown=I.Lg;window.mnu_ms_wbOnEditDown=I.Jg;window.mnu_ms_onLineDashDown=I.Gf;window.mnu_ms_onRectDashOver=I.Tf;window.mnu_ms_onRectDashOut=I.Sf;window.mnu_ms_onLineDashOver=I.If;window.mnu_ms_onLineDashOut=I.Hf;window.mnu_ms_onDashEditDown=I.hf;
window.mnu_ms_onRectGrdDown=I.Jc;window.mnu_ms_bGrdOnUp=I.Wb;window.mnu_ms_bGrdOnDown=I.Vb;window.mnu_ms_bGrdOnBarBackDown=I.Tb;window.mnu_ms_bGrdOnBarDown=I.Ub;window.mnu_ms_onGrdEditDown=I.wc;window.mnu_ms_onGrdTool=I.xc;window.mnu_ms_obOnRectDown=I.tc;window.mnu_ms_obHsOnIndexDown=I.rc;window.mnu_ms_obOnEditDown=I.sc;window.mnu_ms_onSetStrokeLinecap=I.je;window.mnu_ms_onLinecapEditDown=I.Jf;window.mnu_ms_onSetStrokeLinejoin=I.ke;window.mnu_ms_onLinejoinEditDown=I.Kf;
try{window.fill={clear:function(){Y.clear()},setEnabled:function(b,c){Y.D(b);"undefined"!=typeof X&&X.D(c)},setColor:function(b,c){!0==b?"none"==c?Y.J(!0):(Y.R()&&Y.J(!1),Y.ba(c)):(Y.R()&&Y.J(!1),Y.Jb())},setGrd:function(b,c){!0==b?(lc(c),Y.R()&&Y.J(!1),Y.ob(h(c))):(Y.R()&&Y.J(!1),Y.fa())},setOpacity:function(b,c){!0==b?Y.ga(c):Y.S()},setRule:function(b,c){!0==b?Y.we(c):Y.$c()}},window.parent.fill=window.fill}catch(Cc){}
var Y={f:function(){p(M("fill-panel-clip").firstChild,K(M("fill-panel-rect")));Y.Ab="sienna";Y.la=null;Y.Bb=1;Y.e=M("fill-path-area");Y.pd=M("v-fill");Y.Hb=M("plume-fill");Y.sb=(new Va).i("fill-none");Y.Ja=(new Xa).f(Y.pd,Y.Zb);Ya(Y.Ja,"Sienna");Y.gb=(new Xa).f(M("fill-opacity-value"),Y.Qc);Ya(Y.gb,"0.01");Y.q=new OpacityBarCtrl("fill-opacity",Y);Y.ia=M("v-fill-grd");Y.xa=M("plume-fill-grd");Y.v=null;Y.p=(new cb).i("fill-grd");Y.eb();db(Y.p);x(M("g-fill-color-title"),0);x(M("g-fill-opacity-title"),
0);x(M("g-fill-gradient-title"),0);Y.Ce=(new Wa).i("fill-rule-group");Y.Wc=M("fill-rule-plume");Y.Id="evenodd";x(M("fillGrdToolBtn"),1);ia(O(M("fillGrdTool-tip"),"text"),1);Y.sa=new VerticalTab("fill");Y.sa.f();Y.S();Y.ba("sienna");"undefined"!=typeof I&&(I.e=Y.e)},Zb:function(b,c,d){return void 0!=Ka[c]||Ia(c)||Ha(c)?(Y.Eb(c),c):d},Qc:function(b,c,d){return!0==RegExp("[0-1]*( .[0-9]*)?","g").test(c)&&(b=parseFloat(c).toFixed(2),0<=b&&1>=b)?(Y.Oa(b),b):d},eb:function(){oc(Y.p.e);Y.v=Y.p.e.firstChild;
Y.la=sa(G(Y.v))},D:function(b){!0==b?R(M("fill-disabled-rect")):Q(M("fill-disabled-rect"))},isEnabled:function(){return!1==S(M("fill-disabled-rect"))},clear:function(){Y.Jb();Y.fa();Y.S();Y.$c()},R:function(){return Y.sb.j()},J:function(b){Y.sb.g(b);Ba(M("fill-none-rect"),b);!0==b?l(Y.e,"none"):null!=Y.ab()?fa(Y.e,Y.la):l(Y.e,Y.Ab);void 0!=Y.text&&X.isEnabled()&&l(Y.text,G(Y.e))},Sg:function(){return G(Y.e)},ba:function(b){Y.fa();l(M("rouleau-a"),b);l(M("rouleau-b"),b);l(Y.e,b);Y.q.ba(b);Q(Y.Hb);
Q(Y.pd);Y.Ja.g(b);Y.Ab=b;void 0!=Y.text&&X.isEnabled()&&l(Y.text,b)},Oe:function(){!1==S(Y.Hb)&&Y.ba(Y.Ab)},Jb:function(){aa(Y.e);R(Y.Hb);R(Y.pd);void 0!=Y.text&&X.isEnabled()&&aa(Y.text)},ab:function(){if(S(Y.xa)){var b=Y.ia.firstChild.data;return" "==b?null:b}return null},dc:function(b){return pc(M("fill-grd-area"),b)},ob:function(b){Y.Jb();null!=Y.v&&ca(Y.v);fa(M("rouleau-a"),b);fa(M("rouleau-b"),b);fa(Y.e,b);Y.q.ba("sienna");Q(Y.xa);Q(Y.ia);Y.ia.firstChild.data=b;Y.la=b;Y.v=Y.dc(b);null!=Y.v&&
D(Y.v,"0.5px");void 0!=Y.text&&X.isEnabled()&&fa(Y.text,b)},fa:function(){aa(Y.e);R(Y.xa);R(Y.ia);void 0!=Y.text&&X.isEnabled()&&aa(Y.text)},S:function(){f(Y.e,"fill-opacity");Y.q.S();void 0!=Y.text&&X.isEnabled()&&f(Y.text,"fill-opacity")},ga:function(b){m(Y.e,"fill-opacity",b);Y.q.ga(b);void 0!=Y.text&&X.isEnabled()&&m(Y.text,"fill-opacity",b)},Rd:function(){return H(Y.e,"fill-opacity")},Tg:function(){return H(Y.e,"fill-rule")},we:function(b){m(Y.e,"fill-rule",b);var c=M("fill-rule-area");m(c,"fill-rule",
b);Y.Ce.select(b);Y.Id="v";Q(Y.Wc)},$c:function(){f(Y.e,"fill-rule");var b=M("fill-rule-area");f(b,"fill-rule");Y.Ce.P();R(Y.Wc)},Lc:function(b){Y.J(b);$("onSetFill",!0==b?"none":G(Y.e))},Eb:function(b){Y.ba(b);$("onSetFillColor",b)},he:function(b){Y.ob(b);$("onSetFillGrd",M(b))},Oa:function(b){Y.ga(b);$("onSetFillOpacity",b)},Xf:function(){Y.Jb();Z("onRemoveFill")},Zf:function(){Y.fa();Z("onRemoveFillGrd")},de:function(){Y.S();Z("onRemoveFillOpacity")},Gc:function(){Y.Lc(!Y.R())},lf:function(){S(Y.Hb)?
Y.Xf():Y.Eb(Y.Ab)},Ic:function(b){Y.Eb(G(b.target))},Jc:function(b){Y.he(sa(G(b.target)))},wc:function(){null==Y.ab()?Y.he(Y.la):Y.Zf()},xc:function(){Z("onGrdFillTool")},Dc:function(){Y.Le()},Ec:function(b){Y.Eb(b);W.bb();R(M("stylepanel-disabled"))},Fg:function(){Q(M("stylepanel-disabled"));W.show(2,L(M("fill-panel"))+2,1.2,Y.Ec,Y.Dc);W.Ra(G(Y.e))},Le:function(){W.bb();R(M("stylepanel-disabled"))},Cc:function(){Y.Fg()},ge:function(b){Y.we(b);$("onSetFillRule",b)},Yf:function(){Y.$c();Z("onRemoveFillRule")},
mf:function(){S(Y.Wc)?Y.Yf():Y.ge(Y.Id)},vc:function(b){Y.Oe();Y.Ja.onclick(b)},Hc:function(b){Y.q.na();Y.gb.onclick(b)},wb:function(b){Y.sa.I(b)},tc:function(b){Y.q.I(b)},rc:function(b){Ua(Y.q.n,b)},sc:function(b){Y.q.$(b)},Wb:function(){eb(Y.p)},Vb:function(){fb(Y.p)},Tb:function(b){gb(Y.p,b)},Ub:function(b){hb(Y.p,b)}};window.mnu_mf_vtOnRectDown=Y.wb;window.mnu_mf_onFfClick=Y.vc;window.mnu_mf_onOfClick=Y.Hc;window.mnu_mf_onNoneDown=Y.Gc;window.mnu_mf_onRectColorDown=Y.Ic;window.mnu_mf_onLut=Y.Cc;
window.mnu_mf_onFillEditDown=Y.lf;window.mnu_mf_obOnRectDown=Y.tc;window.mnu_mf_obHsOnIndexDown=Y.rc;window.mnu_mf_obOnEditDown=Y.sc;window.mnu_mf_onRectGrdDown=Y.Jc;window.mnu_mf_bGrdOnUp=Y.Wb;window.mnu_mf_bGrdOnDown=Y.Vb;window.mnu_mf_bGrdOnBarBackDown=Y.Tb;window.mnu_mf_bGrdOnBarDown=Y.Ub;window.mnu_mf_onGrdEditDown=Y.wc;window.mnu_mf_onGrdTool=Y.xc;window.mnu_mf_onSetFillRule=Y.ge;window.mnu_mf_onFillRuleEditDown=Y.mf;
try{window.text={clear:function(){X.clear()},setEnabled:function(b){X.D(b)},setFamily:function(b,c){!0==b?X.aa(c):X.lb()},setSize:function(b,c){!0==b?X.Sa(c):X.mb()},setStyle:function(b,c){!0==b?X.ze(c):X.Lb()},setWeight:function(b,c){!0==b?X.Qb(c):X.Qa()},setStretch:function(b,c){!0==b?m(X.text,"font-stretch",c):f(X.text,"font-stretch")},setVariant:function(b,c){!0==b?m(X.text,"font-variant",c):f(X.text,"font-variant")},setAnchor:function(b,c){!0==b?X.ue(c):X.Xc()},setDecoration:function(b,c){!0==
b?X.ve(c):X.Zc()}},window.parent.text=window.text}catch(Dc){}
var X={f:function(){X.text=M("font-text");var b=V(X.text);X.s=Da(b);X.size=b.createSVGLength();p(M("font-panel-clip").firstChild,K(M("font-panel-rect")));X.Ua=(new Xa).f(M("font-size-value"),X.Gg);Ya(X.Ua,"10.00");X.M=new FontFamilyCtrl("font-list",X);X.Ja=(new Xa).f(M("font-list-value"),X.Qe);Ya(X.Ja,"monospace");X.o=new FontSizeBarCtrl("font-size",X);X.o.f();X.Fe=(new Wa).i("font-style-group");X.qe=M("font-style-plume");X.sd=M("font-style-value");X.Rb=M("font-style-text");X.H=new FontWeightCtrl("font-weight",
X);X.H.f();X.Ae=(new Wa).i("font-anchor-group");X.Sc=M("font-anchor-plume");X.Ba=M("font-anchor-text");X.xd=M("font-anchor-xy");X.Be=(new Wa).i("font-decoration-group");X.Uc=M("font-decoration-plume");X.qb=M("font-decoration-text");X.Ld="normal";X.Gd="start";X.Hd="underline";X.aa("serif");X.Sa("10px");X.Lb();X.Qa();X.sa=new VerticalTab("font");X.sa.f();void 0!=Y&&(Y.text=X.text)},Gg:function(b,c,d){return!0==RegExp("[0-9]*( .[0-9]*)?","g").test(c)&&(b=parseFloat(c).toFixed(2),0<=b)?(X.jb(b+X.o.A),
b):d},Qe:function(b,c){X.Kc(c);return c},clear:function(){X.lb();X.Lb();X.mb();X.Qa();X.Xc();X.Zc()},D:function(b){!0==b?R(M("font-disabled-rect")):Q(M("font-disabled-rect"))},isEnabled:function(){return!1==S(M("font-disabled-rect"))},ba:function(b){l(X.text,b)},Rg:function(){return H(X.text,"font-family")},gh:function(){X.M.qa()},ih:function(){X.M.ra()},Pd:function(b){return X.M.Pd(b)},aa:function(b){X.M.aa(b);X.o.aa(b);X.H.aa(b);la(X.text,b);la(X.Rb,b)},lb:function(){X.M.lb();f(X.text,"font-family");
f(X.Rb,"font-family")},Sa:function(b){X.size.valueAsString=b;X.size.valueInSpecifiedUnits*=X.s;ma(X.text,X.size.valueAsString);X.o.Sa(b)},Sd:function(){return H(X.text,"font-size")},mb:function(){X.o.mb();f(X.text,"font-size")},ze:function(b){X.Fe.select(b);m(X.text,"font-style",b);m(X.Rb,"font-style",b);Q(X.qe);Q(X.sd);X.sd.firstChild.data=b;X.Ld=b},We:function(){return H(X.text,"font-style")},Lb:function(){X.Fe.P();f(X.text,"font-style");f(X.Rb,"font-style");R(X.qe);R(X.sd)},ue:function(b){var c=
10*X.Ae.select(b)-20;g(X.xd,"cx",c);t(X.Ba,c);m(X.Ba,"text-anchor",b);Q(X.Sc);Q(X.Ba);Q(X.xd);X.Ba.firstChild.data=b;X.Gd=b},Pg:function(){return X.Ba.getAttribute("text-anchor")},Xc:function(){X.Ae.P();f(X.Ba,"text-anchor");R(X.Sc);R(X.Ba);R(X.xd)},ve:function(b){X.Be.select(b);m(X.qb,"text-decoration",b);m(X.text,"text-decoration",b);Q(X.Uc);Q(X.qb);X.qb.firstChild.data=b;X.Hd=b},Zc:function(){X.Be.P();f(X.qb,"text-decoration");f(X.text,"text-decoration");R(X.Uc);R(X.qb)},ug:function(){null==X.We()?
X.me(X.Ld):X.gg()},hh:function(){X.H.qa()},jh:function(){X.H.ra()},Qd:function(b){return X.H.Qd(b)},Xe:function(){return H(X.text,"font-weight")},Qb:function(b){X.H.Qb(b);m(X.text,"font-weight",b)},Qa:function(){X.H.Qa();f(X.text,"font-weight")},Kc:function(b){X.aa(b);$("onSetFontFamily",b)},Wf:function(){X.lb();Z("onRemoveFontFamily")},jb:function(b){X.Sa(b);if(Pa("onSetFontSize"))window.parent.onSetFontSize(b,X.s)},$f:function(){X.mb();Z("onRemoveFontSize")},me:function(b){X.ze(b);$("onSetFontStyle",
b)},gg:function(){X.Lb();Z("onRemoveFontStyle")},ee:function(b){X.ue(b);$("onSetTextAnchor",b)},Uf:function(){X.Xc();Z("onRemoveTextAnchor")},cf:function(){S(X.Sc)?X.Uf():X.ee(X.Gd)},kf:function(){S(X.Uc)?X.Vf():X.fe(X.Hd)},ne:function(b){X.Qb(b);$("onSetFontWeight",b)},hg:function(){X.Qa();Z("onRemoveFontWeight")},fe:function(b){X.ve(b);$("onSetTextDecoration",b)},Vf:function(){X.Zc();Z("onRemoveTextDecoration")},Oc:function(b){X.o.na();X.Ua.onclick(b)},vc:function(b){X.M.na();X.Ja.onclick(b)},wb:function(b){X.sa.I(b)},
sf:function(b){nb(X.M.m,b)},uf:function(b){ob(b)},tf:function(b){qb(b)},qf:function(){eb(X.M.m.B)},of:function(){fb(X.M.m.B)},nf:function(b){gb(X.M.m.B,b)},pf:function(b){hb(X.M.m.B,b)},rf:function(b){X.M.$(b)},lg:function(b){X.o.I(b)},kg:function(b){Ua(X.o.n,b)},ng:function(){Ab(X.o.V)},mg:function(b){Bb(X.o.V,b)},jg:function(b){X.o.$(b)},Af:function(b){nb(X.H.m,b)},Cf:function(b){ob(b)},Bf:function(b){qb(b)},yf:function(){eb(X.H.m.B)},wf:function(){fb(X.H.m.B)},vf:function(b){gb(X.H.m.B,b)},xf:function(b){hb(X.H.m.B,
b)},zf:function(b){X.H.$(b)}};window.mnu_mt_vtOnRectDown=X.wb;window.mnu_mt_onSfClick=X.Oc;window.mnu_mt_onFfClick=X.vc;window.mnu_mt_onFlNextRectDown=X.sf;window.mnu_mt_onFlNextRectOver=X.uf;window.mnu_mt_onFlNextRectOut=X.tf;window.mnu_mt_onFlBarUp=X.qf;window.mnu_mt_onFlBarBottom=X.of;window.mnu_mt_onFlBarBackDown=X.nf;window.mnu_mt_onFlBarDown=X.pf;window.mnu_mt_onFlEditDown=X.rf;window.mnu_mt_onSbRectDown=X.lg;window.mnu_mt_onSbHsOnIndexDown=X.kg;window.mnu_mt_onSbWuValueDown=X.ng;
window.mnu_mt_onSbWuTextDown=X.mg;window.mnu_mt_onSbEditDown=X.jg;window.mnu_mt_onSetStyle=X.me;window.mnu_mt_onStyleEditDown=X.ug;window.mnu_mt_onFwNextRectDown=X.Af;window.mnu_mt_onFwNextRectOver=X.Cf;window.mnu_mt_onFwNextRectOut=X.Bf;window.mnu_mt_onFwBarUp=X.yf;window.mnu_mt_onFwBarBottom=X.wf;window.mnu_mt_onFwBarBackDown=X.vf;window.mnu_mt_onFwBarDown=X.xf;window.mnu_mt_onFwEditDown=X.zf;window.mnu_mt_onSetAnchor=X.ee;window.mnu_mt_onAnchorEditDown=X.cf;window.mnu_mt_onSetDecoration=X.fe;
window.mnu_mt_onDecorationEditDown=X.kf;try{window.marker={clear:function(){Ec();Fc();Ic()},setEnabled:function(b){!0==b?R(M("marker-disabled-rect")):Q(M("marker-disabled-rect"))},setMarkerStart:function(b,c){!0==b&&null!=c?(mc(c),Jc(h(c))):Ec()},setMarkerMid:function(b,c){!0==b&&null!=c?(mc(c),Kc(h(c))):Fc()},setMarkerEnd:function(b,c){!0==b&&null!=c?(mc(c),Lc(h(c))):Ic()},loadMarkers:function(){ic()}},window.parent.marker=window.marker}catch(Mc){}
function ic(){var b=document.getElementsByTagName("marker");Nc(Pb,b,0);db(bc);Nc(Qb,b,1);db(cc);Nc(Rb,b,2);db(dc)}function Oc(b,c){for(var d=b.firstChild;null!=d;d=d.nextSibling)if("rect"==d.tagName&&ra(d)==c)return d;return null}
function Nc(b,c,d){za(b);for(var k=0,n=1,r=1;k<c.length;k++){var y=h(c[k]);45==n&&(n=1,r+=9);var u,A=b,N=n,P=r,La=y;u=va(A,"path");ga(da(q(p(s(t(va(A,"rect"),N),P),8),10),"tSiennaMarkerList0"),La);A=E(u,"translate("+N+" "+P+")");g(A,"clip-path","url(#marker-rect-clip)");switch(d){case 0:ga(g(u,"d","M5,4h4"),y);break;case 1:u=g(u,"d","M1,4h4h4");m(u,"marker-mid","url(#"+y+")");break;case 2:u=g(u,"d","M1,4h4"),m(u,"marker-end","url(#"+y+")")}n+=11}}
function Jc(b){ga(Sb,b);fc=b;Q(Tb);Q(Ub);Ub.firstChild.data=b;null!=Vb&&T(Vb,"0");Vb=Oc(Pb,b);null!=Vb&&T(Vb,"1")}function Ec(){f(Sb,"marker-start");R(Tb);R(Ub);null!=Vb&&T(Vb,"0");Vb=null}function Fc(){f(Sb,"marker-mid");R(Wb);R(Xb);null!=Yb&&T(Yb,"0");Yb=null}function Ic(){f(Sb,"marker-end");R(Zb);R($b);null!=ac&&T(ac,"0");ac=null}function Kc(b){m(Sb,"marker-mid","url(#"+b+")");ec=b;Q(Wb);Q(Xb);Xb.firstChild.data=b;null!=Yb&&T(Yb,"0");Yb=Oc(Qb,b);null!=Yb&&T(Yb,"1")}
function Lc(b){m(Sb,"marker-end","url(#"+b+")");gc=b;Q(Zb);Q($b);$b.firstChild.data=b;null!=ac&&T(ac,"0");ac=Oc(Rb,b);null!=ac&&T(ac,"1")}function Pc(b){Jc(b);$("onSetMarkerStart",M(b))}function Qc(){Ec();Z("onRemoveStart")}function Rc(b){Kc(b);$("onSetMarkerMid",M(b))}function Sc(b){Lc(b);$("onSetMarkerEnd",M(b))}var nc={},Pb,Qb,Rb,Sb,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,bc,cc,dc,ec,fc,gc,hc;window.mnu_mk_vtOnRectDown=function(b){hc.I(b)};window.mnu_mk_onRectStartDown=function(b){Pc(ra(b.target))};
window.mnu_mk_onBStartLeft=nc.bh;window.mnu_mk_onBStartRight=nc.dh;window.mnu_mk_onBStartBarBackDown=function(b){gb(bc,b)};window.mnu_mk_onBStartBarDown=function(b){hb(bc,b)};window.mnu_mk_onStartEditDown=function(){S(Tb)?Qc():Pc(fc)};window.mnu_mk_onRectMidDown=function(b){Rc(ra(b.target))};window.mnu_mk_onBMidLeft=nc.$g;window.mnu_mk_onBMidRight=nc.ah;window.mnu_mk_onBMidBarBackDown=function(b){gb(cc,b)};window.mnu_mk_onBMidBarDown=function(b){hb(cc,b)};
window.mnu_mk_onMidEditDown=function(){S(Wb)?(Fc(),Z("onRemoveMid")):Rc(ec)};window.mnu_mk_onRectEndDown=function(b){Sc(ra(b.target))};window.mnu_mk_onBEndLeft=nc.Yg;window.mnu_mk_onBEndRight=nc.Zg;window.mnu_mk_onBEndBarBackDown=function(b){gb(dc,b)};window.mnu_mk_onBEndBarDown=function(b){hb(dc,b)};window.mnu_mk_onEndEditDown=function(){S(Zb)?(Ic(),Z("onRemoveEnd")):Sc(gc)};window.mnu_mk_onMarkerEndTool=function(){Z("onMarkerEndTool")};window.mnu_mk_onMarkerMidTool=function(){Z("onMarkerMidTool")};
window.mnu_mk_onMarkerStartTool=function(){Z("onMarkerStartTool")};window.mnu_mk_onRectSampleDown=function(b){var c=ja(b.target,"path");b=ra(c);var d=sa(H(c,"marker-mid")),c=sa(H(c,"marker-end"));null==b?Qc():Pc(b);null==d?(Fc(),Z("onRemoveMid")):Rc(b);null==c?(Ic(),Z("onRemoveEnd")):Sc(c)};var Ac={},kc,jc;window.mnu_mopt_onAnimateDown=function(){ub.close(8);jc.g(tb())};window.mnu_mopt_onSVG12Down=function(){try{kc.g(I.bf()),$("onSvg12Enabled",I.ha)}catch(b){alert("onSVG12Down "+b)}};
	
window.mnuInit();

if (typeof(window.onMnuLoadJS)!='undefined') {	
	window.onMnuLoadJS();
}
